/* MFL Fishing Conditions v14.3.0 — basin-aware live adapters */
(function(){
  'use strict';
  const KEY='mfl_conditions_manual_v2',COMPARE_KEY='mfl_conditions_compare_v1',CACHE_KEY='mfl_conditions_live_cache_v1',DAY_KEY='mfl_conditions_day_v1';
  const regions=[
    {id:'bay-east',name:'東京湾東',icon:'🏙️',lat:35.55,lon:140.02,spots:['ichihara','kemigawa_beach','kisarazu_uchiko']},
    {id:'bay-west',name:'東京湾西',icon:'🌉',lat:35.62,lon:139.80,spots:['wakasu','ariake_west']},
    {id:'boso',name:'房総',icon:'🌊',lat:34.99,lon:139.86,spots:['tateyama_sunset']},
    {id:'kashimanada',name:'鹿島灘',icon:'🌅',lat:35.97,lon:140.69,spots:['kashima']}
  ];
  const profiles={
    ichihara:{lat:35.536,lon:140.069,basin:'養老川流域',basinLat:35.347,basinLon:140.153,exposure:'bay',facility:'管理施設'},
    kemigawa_beach:{lat:35.622,lon:140.040,basin:'花見川・印旛沼流域',basinLat:35.720,basinLon:140.180,exposure:'bay',facility:'一般海岸'},
    wakasu:{lat:35.617,lon:139.833,basin:'荒川・江戸川流域',basinLat:35.790,basinLon:139.850,exposure:'bay',facility:'管理施設'},
    ariake_west:{lat:35.629,lon:139.792,basin:'隅田川・荒川／東京港内',basinLat:35.750,basinLon:139.810,exposure:'harbor',facility:'指定釣り可能エリア'},
    kisarazu_uchiko:{lat:35.382,lon:139.911,basin:'小櫃川・矢那川流域',basinLat:35.330,basinLon:140.020,exposure:'harbor',facility:'公園・港内'},
    tateyama_sunset:{lat:34.987,lon:139.853,basin:'館山湾小河川流域',basinLat:35.000,basinLon:139.900,exposure:'open',facility:'管理桟橋'},
    kashima:{lat:35.965,lon:140.692,basin:'鹿島灘沿岸流域',basinLat:35.980,basinLon:140.550,exposure:'open',facility:'管理施設'},
    urayasu_chidori:{lat:35.632,lon:139.910,basin:'旧江戸川・江戸川流域',basinLat:35.790,basinLon:139.900,exposure:'bay',facility:'開放護岸'},
    edogawa_hosuiro:{lat:35.682,lon:139.934,basin:'江戸川流域',basinLat:35.850,basinLon:139.900,exposure:'river',facility:'河口・放水路'},
    futtsu_area:{lat:35.310,lon:139.814,basin:'富津岬周辺小河川流域',basinLat:35.300,basinLon:139.900,exposure:'bay',facility:'市公式案内エリア'},
    'choshi-marina-coast':{lat:35.706,lon:140.857,basin:'利根川下流・銚子沿岸流域',basinLat:35.800,basinLon:140.650,exposure:'open',facility:'海浜公園周辺'},
    'asahi-ioka-coast':{lat:35.692,lon:140.719,basin:'九十九里北部沿岸流域',basinLat:35.740,basinLon:140.620,exposure:'open',facility:'一般海岸'},
    'onjuku-coast':{lat:35.182,lon:140.357,basin:'御宿・夷隅沿岸流域',basinLat:35.250,basinLon:140.300,exposure:'open',facility:'一般海岸'},
    'kamogawa-coast':{lat:35.107,lon:140.105,basin:'加茂川・鴨川沿岸流域',basinLat:35.150,basinLon:140.050,exposure:'open',facility:'一般海岸'},
    honmoku:{lat:35.430,lon:139.675,basin:'横浜港・大岡川流域',basinLat:35.450,basinLon:139.620,exposure:'harbor',facility:'管理海づり施設'},
    isogo:{lat:35.400,lon:139.639,basin:'横浜南部沿岸流域',basinLat:35.410,basinLon:139.590,exposure:'harbor',facility:'管理海づり施設'},
    daikoku:{lat:35.461,lon:139.682,basin:'横浜港・鶴見川流域',basinLat:35.520,basinLon:139.630,exposure:'harbor',facility:'管理海づり施設'},
    higashiogishima:{lat:35.501,lon:139.768,basin:'多摩川・川崎港流域',basinLat:35.600,basinLon:139.700,exposure:'harbor',facility:'公園釣り施設'},
    umibetsuri:{lat:35.281,lon:139.675,basin:'横須賀東岸小河川流域',basinLat:35.270,basinLon:139.650,exposure:'bay',facility:'管理海辺つり公園'},
    kawarago:{lat:36.548,lon:140.627,basin:'鮎川・日立沿岸流域',basinLat:36.570,basinLon:140.570,exposure:'open',facility:'一般海岸'},
    hiraiso:{lat:36.347,lon:140.621,basin:'那珂川・ひたちなか沿岸流域',basinLat:36.390,basinLon:140.520,exposure:'open',facility:'岩場・磯'}
  };
  const demos={
    ichihara:{weather:'くもり',rainChance:40,rain24h:58,rain48h:82,basinRain24h:74,basinRain48h:108,lightning:'注意',windDir:'南東',windSpeed:5.8,wave:.8,tide:'中潮・上げ',water:'雨後の濁りあり'},
    kemigawa_beach:{weather:'くもり',rainChance:35,rain24h:42,rain48h:65,basinRain24h:61,basinRain48h:90,lightning:'低',windDir:'南',windSpeed:4.8,wave:.6,tide:'中潮',water:'花見川河口の濁り注意'},
    wakasu:{weather:'晴れ',rainChance:20,rain24h:12,rain48h:28,basinRain24h:38,basinRain48h:62,lightning:'低',windDir:'南東',windSpeed:5.5,wave:.7,tide:'中潮',water:'湾奥河川の影響あり'},
    ariake_west:{weather:'晴れ',rainChance:20,rain24h:10,rain48h:24,basinRain24h:34,basinRain48h:57,lightning:'低',windDir:'南',windSpeed:4.2,wave:.3,tide:'中潮',water:'港内・低塩分に注意'},
    kisarazu_uchiko:{weather:'くもり',rainChance:30,rain24h:26,rain48h:45,basinRain24h:41,basinRain48h:68,lightning:'低',windDir:'南西',windSpeed:4.8,wave:.5,tide:'中潮',water:'河川流入に注意'},
    tateyama_sunset:{weather:'晴れ',rainChance:15,rain24h:4,rain48h:12,basinRain24h:9,basinRain48h:18,lightning:'低',windDir:'南西',windSpeed:5.2,wave:1.0,tide:'中潮',water:'通常'},
    kashima:{weather:'晴れ',rainChance:20,rain24h:4,rain48h:8,basinRain24h:6,basinRain48h:12,lightning:'低',windDir:'東',windSpeed:6.6,wave:1.4,tide:'中潮・下げ',water:'やや濁り'}
  };
  const fallback={weather:'未取得',rainChance:null,rain24h:null,rain48h:null,basinRain24h:null,basinRain48h:null,lightning:'不明',windDir:'—',windSpeed:null,wave:null,tide:'既存潮汐表を確認',water:'不明',facilityStatus:'未確認',officialWarning:'未接続',updated:'データ未設定'};
  const weatherLabels={0:'快晴',1:'晴れ',2:'一部くもり',3:'くもり',45:'霧',48:'霧',51:'霧雨',53:'霧雨',55:'強い霧雨',61:'雨',63:'雨',65:'強い雨',80:'にわか雨',81:'にわか雨',82:'強いにわか雨',95:'雷雨',96:'雷雨',99:'激しい雷雨'};
  const degToDir=d=>['北','北東','東','南東','南','南西','西','北西'][Math.round(Number(d||0)/45)%8];
  const num=v=>Number.isFinite(Number(v))?Number(v):null;
  function read(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch(_){return{}}}
  function sumTail(values,hours){return (values||[]).slice(-hours).reduce((a,v)=>a+(num(v)||0),0)}
  async function fetchJSON(url,timeout=7000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const res=await fetch(url,{signal:controller.signal});if(!res.ok)throw new Error(`HTTP ${res.status}`);return await res.json()}finally{clearTimeout(timer)}}
  let tideTablePromise;
  function localDateKey(offset=0){const date=new Date();date.setDate(date.getDate()+offset);return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
  async function tideForDay(offset=0){const table=await(tideTablePromise||(tideTablePromise=fetchJSON('./data/tides-2026.json'))),date=localDateKey(offset),day=table.stations?.TK?.days?.[date];if(!day)return{label:'潮位表の対象外',station:'東京基準',date};const hour=offset?12:new Date().getHours(),level=day.hourly?.[hour],before=day.hourly?.[Math.max(0,hour-1)],after=day.hourly?.[Math.min(23,hour+1)],delta=(num(after)||0)-(num(before)||0),phase=delta>4?'上げ潮':delta<-4?'下げ潮':'潮止まり付近';return{label:`${phase}・${level??'—'}cm`,station:'東京基準（天文潮位）',date,phase,level,highs:day.highs||[],lows:day.lows||[]}}
  function forecastURL(lat,lon){return `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=weather_code,wind_speed_10m,wind_direction_10m&hourly=precipitation,precipitation_probability,weather_code&past_hours=48&forecast_hours=12&wind_speed_unit=ms&timezone=Asia%2FTokyo`}
  function marineURL(lat,lon){return `https://marine-api.open-meteo.com/v1/marine?latitude=${lat}&longitude=${lon}&current=wave_height&hourly=wave_height&forecast_hours=12&timezone=Asia%2FTokyo&cell_selection=sea`}
  function weeklyURL(lat,lon){return `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,wind_speed_10m_max,wind_gusts_10m_max&wind_speed_unit=ms&timezone=Asia%2FTokyo&forecast_days=7`}
  function marineWeeklyURL(lat,lon){return `https://marine-api.open-meteo.com/v1/marine?latitude=${lat}&longitude=${lon}&daily=wave_height_max&timezone=Asia%2FTokyo&forecast_days=7&cell_selection=sea`}
  async function openMeteo(spot,dayOffset=0){
    const p=profiles[spot.id];if(!p)throw new Error('地点プロファイル未登録');
    if(dayOffset>0){const [local,basin,marine,tideInfo]=await Promise.all([fetchJSON(weeklyURL(p.lat,p.lon)),fetchJSON(weeklyURL(p.basinLat,p.basinLon)),fetchJSON(marineWeeklyURL(p.lat,p.lon)).catch(()=>({})),tideForDay(dayOffset).catch(()=>null)]);const ld=local.daily,bd=basin.daily,i=Math.min(6,dayOffset),basinToDate=(bd.precipitation_sum||[]).slice(Math.max(0,i-1),i+1).reduce((a,v)=>a+(num(v)||0),0);return{...fallback,weather:weatherLabels[ld.weather_code[i]]||'—',rainChance:num(ld.precipitation_probability_max[i]),rain24h:num(ld.precipitation_sum[i]),rain48h:+basinToDate.toFixed(1),basinRain24h:num(bd.precipitation_sum[i]),basinRain48h:+basinToDate.toFixed(1),lightning:Number(ld.weather_code[i])>=95?'高':'低',windDir:'日平均',windSpeed:num(ld.wind_speed_10m_max[i]),wave:num(marine.daily?.wave_height_max?.[i]),tide:tideInfo?.label||fallback.tide,tideInfo,water:'予想流域雨量から推定',facilityStatus:'当日の公式確認が必要',officialWarning:'当日の気象庁情報を確認',updated:`${ld.time[i]} 予報`,profile:p,forecastDay:i}}
    const [local,basin,marine,tideInfo]=await Promise.all([fetchJSON(forecastURL(p.lat,p.lon)),fetchJSON(forecastURL(p.basinLat,p.basinLon)),fetchJSON(marineURL(p.lat,p.lon)).catch(()=>({})),tideForDay(0).catch(()=>null)]);
    const localPast=(local.hourly?.precipitation||[]).slice(0,48),basinPast=(basin.hourly?.precipitation||[]).slice(0,48),futureCodes=(local.hourly?.weather_code||[]).slice(-12),futureRain=(local.hourly?.precipitation_probability||[]).slice(-12);
    return {...fallback,weather:weatherLabels[local.current?.weather_code]||'天候コード '+local.current?.weather_code,rainChance:Math.max(0,...futureRain.map(x=>num(x)||0)),rain24h:+sumTail(localPast,24).toFixed(1),rain48h:+sumTail(localPast,48).toFixed(1),basinRain24h:+sumTail(basinPast,24).toFixed(1),basinRain48h:+sumTail(basinPast,48).toFixed(1),lightning:futureCodes.some(x=>Number(x)>=95)?'高':'低',windDir:degToDir(local.current?.wind_direction_10m),windSpeed:num(local.current?.wind_speed_10m),wave:num(marine.current?.wave_height),tide:tideInfo?.label||fallback.tide,tideInfo,water:'流域雨量から推定',facilityStatus:'公式確認が必要',officialWarning:'気象庁情報を確認',updated:new Date().toLocaleString('ja-JP'),profile:p};
  }
  async function warnings(spot){if(typeof window.MFL_WARNING_ADAPTER!=='function')return{};return await window.MFL_WARNING_ADAPTER(spot)}
  const adapters={
    openMeteo:{name:'Open-Meteo 実データ',get:openMeteo},
    warnings:{name:'気象庁・施設情報接続口',get:warnings},
    manual:{name:'手動 / デモ',async get(spot){return {...fallback,...(demos[spot.id]||{}),...(read(KEY)[spot.id]||{}),profile:profiles[spot.id],updated:(read(KEY)[spot.id]?.updated)||'デモデータ'}}}
  };
  async function get(spot){
    const day=Math.max(0,Math.min(6,Number(localStorage.getItem(DAY_KEY)||0))),cacheId=`${spot.id}:${day}`;
    try{const live=await adapters.openMeteo.get(spot,day),safe=await adapters.warnings.get(spot);const data={...live,...safe,source:'live'};const cache=read(CACHE_KEY);cache[cacheId]=data;localStorage.setItem(CACHE_KEY,JSON.stringify(cache));return data}
    catch(_){const manual=read(KEY)[spot.id];if(manual&&day===0)return{...fallback,...manual,profile:profiles[spot.id],source:'manual'};const cached=read(CACHE_KEY)[cacheId];if(cached)return{...cached,source:'cache'};return{...await adapters.manual.get(spot),source:'demo'}}
  }
  async function weeklyRegion(region){const j=await fetchJSON(weeklyURL(region.lat,region.lon));return j.daily.time.map((date,i)=>({date,code:j.daily.weather_code[i],weather:weatherLabels[j.daily.weather_code[i]]||'—',max:j.daily.temperature_2m_max[i],min:j.daily.temperature_2m_min[i],rain:j.daily.precipitation_probability_max[i],rainSum:j.daily.precipitation_sum[i],wind:j.daily.wind_speed_10m_max[i],gust:j.daily.wind_gusts_10m_max[i]}))}
  function dayGrade(rows){const rain=Math.max(...rows.map(x=>num(x.rain)||0)),wind=Math.max(...rows.map(x=>num(x.wind)||0)),storm=rows.some(x=>Number(x.code)>=95);if(storm||wind>=10||rain>=80)return['×','見送り候補','stop'];if(wind>=7||rain>=60)return['△','慎重に','careful'];if(wind>=5||rain>=35)return['○','条件付き','good'];return['◎','候補日','great']}
  function shortDate(s){const d=new Date(`${s}T00:00:00`),days=['日','月','火','水','木','金','土'];return`${d.getMonth()+1}/${d.getDate()}(${days[d.getDay()]})`}
  async function mountWeekly(id,navigate){const root=document.getElementById(id);if(!root)return;root.innerHTML='<section class="weekly-shell"><div class="weekly-head"><div><small>KANTO COAST 7 DAYS</small><h3>関東沿岸・7日間</h3></div><span>LIVE</span></div><div class="fc-loading">週間予報を取得中…</div></section>';try{const all=await Promise.all(regions.map(weeklyRegion));root.innerHTML=`<section class="weekly-shell"><div class="weekly-head"><div><small>KANTO COAST 7 DAYS</small><h3>関東沿岸・7日間</h3><p>いつ行けそうかを探す。詳しい判断はコンディションへ。</p></div><span>LIVE</span></div><div class="weekly-scroll">${all[0].map((_,day)=>{const rows=all.map(x=>x[day]),g=dayGrade(rows),best=regions.map((r,i)=>({r,row:rows[i],score:(num(rows[i].rain)||0)+(num(rows[i].wind)||0)*7})).sort((a,b)=>a.score-b.score)[0];return`<button class="weekly-day ${g[2]}" data-week-day="${day}"><div class="weekly-date"><strong>${shortDate(rows[0].date)}</strong><b>${g[0]}</b></div><div class="weekly-icon">${Number(rows[0].code)>=95?'⛈️':Number(rows[0].code)>=61?'🌧️':Number(rows[0].code)>=2?'⛅':'☀️'}</div><span>${g[1]}</span><dl><div><dt>雨</dt><dd>${Math.round(Math.max(...rows.map(x=>x.rain||0)))}%</dd></div><div><dt>風</dt><dd>${Math.max(...rows.map(x=>x.wind||0)).toFixed(1)}m</dd></div></dl><small>候補 ${best.r.icon}${best.r.name}</small></button>`}).join('')}</div><div class="weekly-region-legend">${regions.map(x=>`<span>${x.icon}${x.name}</span>`).join('')}</div><p class="weekly-note">関東沿岸の広域目安です。カードを押すと同日の詳細比較を開きます。</p></section>`;root.querySelectorAll('[data-week-day]').forEach(b=>b.onclick=()=>{localStorage.setItem(DAY_KEY,b.dataset.weekDay);localStorage.setItem('mfl_open_conditions','1');navigate()})}catch(_){root.innerHTML='<section class="weekly-shell"><div class="weekly-head"><div><small>KANTO COAST 7 DAYS</small><h3>関東沿岸・7日間</h3></div></div><p class="weekly-note">週間予報を取得できませんでした。通信回復後に自動更新します。</p></section>'}}
  function evaluate(d){
    let score=100;const reasons=[];const rain=num(d.rainChance),local24=num(d.rain24h),basin24=num(d.basinRain24h),basin48=num(d.basinRain48h),wind=num(d.windSpeed),wave=num(d.wave);let hardStop=false;
    if(d.regulation==='禁止'||d.facilityStatus==='閉鎖'){hardStop=true;reasons.push(d.regulation==='禁止'?'釣り禁止':'施設閉鎖')}
    if(/特別警報|警報/.test(d.officialWarning||'')){hardStop=true;reasons.push(d.officialWarning)}
    if(d.lightning==='高'||d.lightning==='警報'){score-=70;reasons.push('雷リスクが高い')}else if(d.lightning==='注意'){score-=25;reasons.push('雷に注意')}
    if(wind!==null){if(wind>=10){score-=55;reasons.push(`風${wind}m/s`)}else if(wind>=7){score-=30;reasons.push(`強めの風${wind}m/s`)}else if(wind>=5){score-=12;reasons.push(`風${wind}m/s`)}}
    if(wave!==null){if(wave>=2){score-=55;reasons.push(`波${wave}m`)}else if(wave>=1.5){score-=28;reasons.push(`波高め${wave}m`)}else if(wave>=1){score-=12;reasons.push(`波${wave}m`)}}
    if(rain!==null){if(rain>=70){score-=25;reasons.push(`降水${rain}%`)}else if(rain>=40){score-=12;reasons.push(`降水${rain}%`)}}
    if(basin24!==null&&basin24>=60){score-=32;reasons.push(`流域24h ${basin24}mm`)}else if(basin24!==null&&basin24>=30){score-=20;reasons.push(`流域24h ${basin24}mm`)}else if(basin48!==null&&basin48>=50){score-=12;reasons.push(`流域48h ${basin48}mm`)}
    if(local24!==null&&local24>=50){score-=18;reasons.push(`現地24h ${local24}mm`)}else if(local24!==null&&local24>=20){score-=9;reasons.push(`現地24h ${local24}mm`)}
    if(hardStop)score=0;const rank=score>=82?['◎','行きやすい','great']:score>=62?['○','条件付き','good']:score>=38?['△','慎重に','careful']:['×','見送り','stop'];
    return{score:Math.max(0,score),symbol:rank[0],label:rank[1],className:rank[2],reasons:reasons.length?reasons:['大きな注意要素なし'],heavyRain:(basin24||0)>=30||(basin48||0)>=50,hardStop};
  }
  function advice(d,r){if(r.className==='stop')return{weight:'釣行を優先せず見送り',worm:'—',method:'警報・施設発表と安全確保を優先'};const strong=(num(d.windSpeed)||0)>=5,muddy=r.heavyRain||/濁/.test(d.water||'');return{weight:strong?'14gを軸に、扱いづらければ中止':'7gから開始',worm:muddy?'アピール強め（チャート・グロー・波動）':'クリア/ナチュラル系から',method:strong?'風上への無理なキャストを避け、足元〜風下を探る':'表層→中層→底の順で反応を確認'}}
  function metric(icon,label,value){return `<div class="fc-metric"><span>${icon}</span><small>${label}</small><strong>${value??'—'}</strong></div>`}
  function sourceLabel(s){return s==='live'?'LIVE API':s==='cache'?'保存済みAPI':s==='manual'?'手動':'デモ'}
  function officialLinks(spot,d){const warning=d.warningURL||'https://www.jma.go.jp/bosai/warning/';return `<div class="fc-official-links"><a href="${warning}" target="_blank" rel="noopener">気象庁の警報を確認</a>${spot.official?`<a href="${spot.official}" target="_blank" rel="noopener">施設・釣り場の公式情報</a>`:''}</div>`}
  function card(spot,d,compact=false){const r=evaluate(d),a=advice(d,r),p=d.profile||profiles[spot.id];return `<article class="fc-card ${r.className}${compact?' compact':''}"><div class="fc-head"><div><small>MFL FISHING CONDITIONS</small><h4>${spot.short||spot.name}</h4></div><div class="fc-rank"><b>${r.symbol}</b><span>${r.label}</span></div></div>
  <div class="fc-metrics">${metric('🌤️','天気',d.weather)}${metric('☔','降水',d.rainChance==null?'—':d.rainChance+'%')}${metric('⚡','雷',d.lightning)}${metric('💨','風',d.windSpeed==null?'—':`${d.windDir} ${d.windSpeed}m/s`)}${metric('🌊','波',d.wave==null?'—':d.wave+'m')}${metric('🌙','潮',d.tide)}</div>${d.tideInfo?`<div class="fc-tide-detail"><div><small>潮位・潮回りの参考</small><strong>${d.tideInfo.station}</strong></div><span>満潮 ${d.tideInfo.highs.map(x=>`${x.time} ${x.level}cm`).join(' / ')||'—'}</span><span>干潮 ${d.tideInfo.lows.map(x=>`${x.time} ${x.level}cm`).join(' / ')||'—'}</span></div>`:''}
  ${p?`<div class="fc-basin"><div><small>流入河川・流域</small><strong>${p.basin}</strong></div><span>24h ${d.basinRain24h??'—'}mm</span><span>48h ${d.basinRain48h??'—'}mm</span></div>`:'<div class="fc-profile-missing">流域プロファイル未登録：手動データで判定</div>'}
  ${r.heavyRain?`<div class="fc-rain-alert"><b>⚠️ 流域の大雨影響</b><span>河川流入・濁り・淡水・漂流物が24〜48時間残る可能性があります。</span></div>`:''}
  ${r.hardStop?`<div class="fc-stop-alert">安全・規制条件により天候点数より優先して「見送り」です。</div>`:''}<div class="fc-reasons">${r.reasons.map(x=>`<span>${x}</span>`).join('')}</div>
  ${compact?'':`<div class="fc-safety"><span>施設 ${d.facilityStatus}</span><span>警報 ${d.officialWarning}</span></div>${officialLinks(spot,d)}<div class="fc-assist"><small>MFL ASSIST（実釣学習前の基礎提案）</small><div><b>⚖️ ${a.weight}</b><b>🪱 ${a.worm}</b></div><p>${a.method}</p></div><div class="fc-source"><span>${sourceLabel(d.source)}・Open-Meteo / 気象庁</span><span>${d.updated}</span></div>`}</article>`}
  async function mountSpot(id,spot,spots){const root=document.getElementById(id);if(!root)return;root.innerHTML='<div class="fc-loading">実データを取得中…</div>';const d=await get(spot);root.innerHTML=card(spot,d)+`<div class="fc-actions single"><button data-fc-manual>手動で補正</button></div><p class="fc-disclaimer">参考判定です。気象庁の警報・施設発表・現地規制を必ず優先してください。</p>`;root.querySelector('[data-fc-manual]').onclick=()=>openManual(spot,d,()=>mountSpot(id,spot,spots))}
  const mapPositions={kashima:[78,16],wakasu:[38,37],ariake_west:[30,43],kemigawa_beach:[55,42],ichihara:[58,55],kisarazu_uchiko:[45,65],tateyama_sunset:[52,88],urayasu_chidori:[53,36],edogawa_hosuiro:[58,31],futtsu_area:[45,72],'choshi-marina-coast':[82,38],'asahi-ioka-coast':[78,48],'onjuku-coast':[72,72],'kamogawa-coast':[64,82],honmoku:[24,57],isogo:[23,63],daikoku:[28,52],higashiogishima:[32,48],umibetsuri:[24,76],kawarago:[72,6],hiraiso:[70,12]};
  function mapSummary(rows){const counts={great:0,good:0,careful:0,stop:0};rows.forEach(x=>counts[evaluate(x.d).className]++);return`<div class="cm-summary"><span class="great"><b>${counts.great}</b> ◎</span><span class="good"><b>${counts.good}</b> ○</span><span class="careful"><b>${counts.careful}</b> △</span><span class="stop"><b>${counts.stop}</b> ×</span></div>`}
  function initializeRealMap(box,rows,selectSpot){if(!window.L)return false;try{const map=L.map(box,{zoomControl:true,attributionControl:true,minZoom:7,maxZoom:16});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);const bounds=[];rows.forEach(x=>{const p=profiles[x.s.id],r=evaluate(x.d);bounds.push([p.lat,p.lon]);const icon=L.divIcon({className:'cm-leaflet-wrap',html:`<button class="cm-leaflet-pin ${r.className}" aria-label="${x.s.name} ${r.label}"><b>${r.symbol}</b><span>${x.s.short||x.s.name}</span></button>`,iconSize:[72,48],iconAnchor:[36,24]});L.marker([p.lat,p.lon],{icon,title:x.s.name}).addTo(map).on('click',()=>selectSpot(x.s.id))});map.fitBounds(bounds,{padding:[28,28],maxZoom:9});setTimeout(()=>map.invalidateSize(),80);return true}catch(_){return false}}
  async function renderConditionsMap(root,spots){const box=root.querySelector('.conditions-map-body');box.innerHTML='<div class="fc-loading">14地点のコンディションを取得中…</div>';const usable=spots.filter(s=>profiles[s.id]),rows=await Promise.all(usable.map(async s=>({s,d:await get(s)})));box.innerHTML=`${mapSummary(rows)}<div id="conditionsRealMap" class="conditions-real-map" aria-label="MFLコンディション実地図"></div><div id="conditionsFallbackMap" class="conditions-map-canvas" hidden><span class="cm-sea">PACIFIC</span><span class="cm-bay">東京湾</span>${rows.map(x=>{const r=evaluate(x.d),p=mapPositions[x.s.id]||[50,50];return`<button class="cm-pin ${r.className}" data-condition-spot="${x.s.id}" style="left:${p[0]}%;top:${p[1]}%"><b>${r.symbol}</b><span>${x.s.short||x.s.name}</span></button>`}).join('')}</div><div class="cm-map-note"><span>実地図・正確な緯度経度</span><button id="toggleFallbackMap">模式図に切替</button></div><div class="cm-legend"><span><i class="great">◎</i>行きやすい</span><span><i class="good">○</i>条件付き</span><span><i class="careful">△</i>慎重に</span><span><i class="stop">×</i>見送り</span></div><div class="conditions-spot-list">${rows.map(x=>{const r=evaluate(x.d);return`<button data-condition-spot="${x.s.id}"><span class="cm-list-rank ${r.className}">${r.symbol}</span><div><strong>${x.s.name}</strong><small>${r.reasons.slice(0,2).join(' / ')}</small></div><b>›</b></button>`}).join('')}</div><section class="conditions-map-detail"><div class="cm-detail-empty"><span>🗺️</span><strong>釣り場を選択</strong><p>地図の判定を押すと、風・波・雷・雨・流域雨量を詳しく表示します。</p></div></section>`;const detail=box.querySelector('.conditions-map-detail'),selectSpot=id=>{const row=rows.find(x=>x.s.id===id);box.querySelectorAll('[data-condition-spot]').forEach(x=>x.classList.toggle('selected',x.dataset.conditionSpot===id));detail.innerHTML=card(row.s,row.d);detail.scrollIntoView({behavior:'smooth',block:'nearest'})};box.querySelectorAll('[data-condition-spot]').forEach(btn=>btn.onclick=()=>selectSpot(btn.dataset.conditionSpot));const real=box.querySelector('#conditionsRealMap'),fallback=box.querySelector('#conditionsFallbackMap'),toggle=box.querySelector('#toggleFallbackMap');if(!initializeRealMap(real,rows,selectSpot)){real.hidden=true;fallback.hidden=false;toggle.textContent='実地図を再試行'}toggle.onclick=()=>{const showFallback=fallback.hidden;fallback.hidden=!showFallback;real.hidden=showFallback;toggle.textContent=showFallback?'実地図に戻す':'模式図に切替'}}
  function mountHub(id,spots){const root=document.getElementById(id);if(!root)return;const selected=Number(localStorage.getItem(DAY_KEY)||0);root.innerHTML=`<section class="fc-hub conditions-map-hub"><div class="fc-hub-title"><div><small>MFL CONDITIONS MAP</small><h3>関東沿岸コンディション</h3><p>各釣り場の「行けそう」を、同じ基準で地図に表示。</p></div><span>${Object.keys(profiles).length}地点</span></div><div class="fc-day-tabs">${Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return`<button data-fc-day="${i}" class="${i===selected?'active':''}">${i===0?'今日':`${d.getMonth()+1}/${d.getDate()}`}</button>`}).join('')}</div><div class="fc-provider-status"><span>天気・雨量 LIVE</span><span>波 LIVE</span><span>流域判定</span></div><div class="conditions-map-body"></div><p class="fc-disclaimer">未対応地点へ推測判定は出しません。警報・施設発表・現地規制を優先してください。</p></section>`;root.querySelectorAll('[data-fc-day]').forEach(x=>x.onclick=()=>{localStorage.setItem(DAY_KEY,x.dataset.fcDay);mountHub(id,spots)});renderConditionsMap(root,spots)}
  function openManual(spot,current,done){const raw=prompt(`${spot.short||spot.name}の補正\n天気,降水%,現地24h,流域24h,流域48h,雷,風向,風速,波,潮,水色,施設状態,警報`,[current.weather,current.rainChance,current.rain24h,current.basinRain24h,current.basinRain48h,current.lightning,current.windDir,current.windSpeed,current.wave,current.tide,current.water,current.facilityStatus,current.officialWarning].join(','));if(raw==null)return;const v=raw.split(',').map(x=>x.trim());if(v.length<13){alert('13項目をカンマ区切りで入力してください');return}const all=read(KEY);all[spot.id]={weather:v[0],rainChance:num(v[1]),rain24h:num(v[2]),basinRain24h:num(v[3]),basinRain48h:num(v[4]),lightning:v[5],windDir:v[6],windSpeed:num(v[7]),wave:num(v[8]),tide:v[9],water:v[10],facilityStatus:v[11],officialWarning:v[12],updated:new Date().toLocaleString('ja-JP')};localStorage.setItem(KEY,JSON.stringify(all));done()}
  window.MFLConditions={profiles,regions,adapters,get,evaluate,advice,mountSpot,mountHub,mountWeekly};
})();
