'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),root=__dirname+'/..';global.window=global;console.warn=()=>{};
window.MFLTides={getHourlyTideFeatures:()=>Array.from({length:24},(_,hour)=>({level:80+hour,phase:hour<12?'上げ潮':'下げ潮',delta:hour<12?4:-4}))};
['forecast-restrictions.js','forecast-validation.js','forecast-features.js','forecast-engine.js','forecast-data.js','forecast-confidence-experimental.js','forecast-engine-experimental.js'].forEach(file=>vm.runInThisContext(fs.readFileSync(`${root}/js/forecast/${file}`,'utf8'),{filename:file}));
const baselines=JSON.parse(fs.readFileSync(`${root}/data/fishing-forecast-baselines.json`)),spots=JSON.parse(fs.readFileSync(`${root}/data/fishing-forecast-spots.json`)),expansion=JSON.parse(fs.readFileSync(`${root}/data/fishing-forecast-expansion.json`)),feedback=JSON.parse(fs.readFileSync(`${root}/data/fishing-forecast-feedback-experimental.json`)),evidenceCatalog=JSON.parse(fs.readFileSync(`${root}/data/fishing-forecast-evidence-experimental.json`)),phase2Evidence=JSON.parse(fs.readFileSync(`${root}/data/fishing-forecast-evidence-phase2-experimental.json`));
Object.entries(phase2Evidence.spots).forEach(([spotId,addition])=>{const base=evidenceCatalog.spots[spotId]||{};evidenceCatalog.spots[spotId]={...base,...addition,sources:[...(base.sources||[]),...(addition.sources||[])],observations:[...(base.observations||[]),...(addition.observations||[])],models:{...(base.models||{}),...(addition.models||{})}}});feedback.evidenceCatalog=evidenceCatalog;
const merged=MFLForecastData.withExpansion(baselines,spots,expansion),config=MFLForecastValidation.validate(merged.baselines,merged.spots),spotIds=Object.keys(config.spots.spots);assert.equal(spotIds.length,22);
assert.equal(phase2Evidence.version,'3.0.0-experimental');Object.entries(phase2Evidence.spots).forEach(([spotId,spot])=>{assert.ok(spotIds.includes(spotId));(spot.sources||[]).forEach(source=>{assert.ok(/^https:\/\//.test(source.url));assert.ok(source.publisher);assert.ok(source.retrievedAt)});(spot.observations||[]).forEach(observation=>{assert.ok(observation.date);assert.ok(['pelagic','bottom','other'].includes(observation.speciesGroup));assert.equal(typeof observation.timeKnown,'boolean')})});
const weather={sunrise:'2026-08-23T05:05',sunset:'2026-08-23T18:18',hourly:Array.from({length:24},(_,hour)=>({hour,windSpeed:2,rain:0,wave:.5})),safety:{hardStop:false}},tideDay={hourly:[],highs:[{time:'06:00'}],lows:[{time:'12:00'}]};
function pair(spotId,date='2026-08-23',weatherInput=weather,data=feedback){const features=MFLForecastFeatures.normalize({spotId,date,baseline:config.baselines.spots[spotId],spotProfile:config.spots.spots[spotId],tideDay,weather:weatherInput}),current=MFLForecastEngine.predict(features,{baselineVersion:merged.baselines.version,baselineLastUpdated:merged.baselines.updated}),experimental=MFLForecastExperimental.compare(features,current,data);return{features,current,experimental}}
const comparisons=spotIds.map(spotId=>({spotId,...pair(spotId)}));comparisons.forEach(({current,experimental})=>{assert.equal(current.engineVersion,'1.3.0');assert.equal(experimental.engineVersion,'1.4.0-experimental');assert.equal(experimental.hours.length,24);experimental.hours.forEach((hour,index)=>{assert.ok(Math.abs(hour.rawScore-current.hours[index].rawScore)<=8);assert.ok(['pelagic','bottom','other'].every(group=>hour.experimentalDebug.modelAdjustments[group]));if(current.hours[index].confidence==='low')Object.values(hour.experimentalDebug.modelAdjustments).forEach(model=>assert.ok(model.totalAdjustment<=3))})});
assert.equal(Object.keys(evidenceCatalog.spots).length,22);const confidenceAudit={};spotIds.forEach(spotId=>{confidenceAudit[spotId]={};['pelagic','bottom','other'].forEach(group=>{const baselineEvidence=config.baselines.spots[spotId].models[group].season?.['08']?.evidence||config.baselines.spots[spotId].models[group].evidence||{},supplemental=MFLForecastConfidenceExperimental.evidenceFor(evidenceCatalog,spotId,group),evidence=supplemental||{...baselineEvidence,traceableSourceCount:0,multiDayCount:0,modelSpecific:true,sourceQuality:'supporting'},field=(feedback.fieldFeedback||[]).filter(item=>item.spotId===spotId&&(item.modelSignals?.[group]||item.speciesGroup===group)),v2=MFLForecastConfidenceExperimental.evaluate(evidence,'2026-08-23',field);confidenceAudit[spotId][group]={before:baselineEvidence.confidence||'low',after:v2.value,points:v2.points,...v2.inputs,observedSpecies:evidence.observedSpecies||[],reason:evidence.reason||baselineEvidence.reasonLabel||'地域季節テンプレートのみ',fieldFeedback:field.map(item=>item.type)}})});assert.equal(Object.values(confidenceAudit).flatMap(Object.values).length,66);
const kashima=comparisons.find(item=>item.spotId==='kashima');[15,16,17,18,19].forEach(hour=>{const debug=kashima.experimental.hours[hour].experimentalDebug.modelAdjustments;assert.ok(debug.bottom.fieldFeedbackAdjustment<=.5);assert.ok(debug.pelagic.fieldFeedbackAdjustment<=.75);assert.equal(kashima.experimental.hours[hour].targetSpecies.includes('フグ'),false)});const surfaceSignals=kashima.experimental.hours[17].experimentalDebug.modelAdjustments.pelagic.fieldFeedbackSignals;assert.ok(surfaceSignals.some(signal=>signal.type==='surfaceActivity'&&signal.species===null&&!signal.speciesConfirmed));
const noData=pair('kashima','2026-08-23',weather,{recentCatchSignals:[],fieldFeedback:[]});assert.ok(noData.experimental.hours.every((hour,index)=>Math.abs(hour.rawScore-noData.current.hours[index].rawScore)<=2));
const promotionCandidate=kashima.current.hours.filter(hour=>hour.score<3&&hour.models[hour.dominantGroup].confidence!=='low').sort((a,b)=>b.rawScore-a.rawScore)[0];if(promotionCandidate){const singleCatch={recentCatchSignals:[{id:'single-promotion-guard',spotId:'kashima',speciesGroup:promotionCandidate.dominantGroup,observedAt:'2026-08-23',startHour:promotionCandidate.hour,endHour:promotionCandidate.hour,weight:3}],fieldFeedback:[]},guarded=pair('kashima','2026-08-23',weather,singleCatch);assert.ok(guarded.experimental.hours[promotionCandidate.hour].score<3)}
const missing=MFLForecastExperimental.compare([],kashima.current,feedback);assert.equal(missing.fallbackToV13,true);assert.deepEqual(missing.hours,kashima.current.hours);
const unsafe=pair('kashima','2026-08-23',{...weather,safety:{hardStop:true}},feedback);assert.ok(unsafe.experimental.hours.every(hour=>hour.score===0&&!hour.recommended&&hour.experimentalDebug.safetyStopped));
const isolatedSignal={recentCatchSignals:[{id:'only-pelagic',spotId:'kashima',speciesGroup:'pelagic',observedAt:'2026-08-23',startHour:5,endHour:5,weight:3}],fieldFeedback:[]},isolated=pair('kashima','2026-08-23',weather,isolatedSignal),isolatedDebug=isolated.experimental.hours[5].experimentalDebug.modelAdjustments;assert.ok(isolatedDebug.pelagic.recentCatchAdjustment>0);assert.equal(isolatedDebug.bottom.recentCatchAdjustment,0);assert.equal(isolatedDebug.other.recentCatchAdjustment,0);
const staleEvidence={lastUpdated:'2024-01-01',sampleCount:20,sourceCount:3,hourlyEvidence:true,confidence:'high'},freshness=MFLForecastExperimental.freshnessAdjustment(staleEvidence,'2026-08-23');assert.equal(freshness.value,-6);
assert.equal(MFLForecastExperimental.decay(7),1);assert.equal(MFLForecastExperimental.decay(14),.75);assert.equal(MFLForecastExperimental.decay(30),.4);assert.equal(MFLForecastExperimental.decay(31),0);const catchCap=MFLForecastExperimental.recentCatchAdjustment('kashima','pelagic',5,'2026-08-23',{sampleCount:20,sourceCount:3,hourlyEvidence:true,confidence:'high'},Array.from({length:5},(_,index)=>({id:`cap-${index}`,spotId:'kashima',speciesGroup:'pelagic',observedAt:'2026-08-23',startHour:5,endHour:5,weight:3})));assert.equal(catchCap.value,6);
const transitions=[],spotSummary={};let rawUnchanged=0,rawSmall=0,rawLarge=0,levelUnchanged=0,levelSmall=0,levelLarge=0,level3Current=0,level3Experimental=0;comparisons.forEach(({spotId,current,experimental})=>{spotSummary[spotId]={unchanged:0,small:0,large:0};experimental.hours.forEach((hour,index)=>{const before=current.hours[index],rawDelta=hour.rawScore-before.rawScore,levelDelta=hour.score-before.score;if(before.score===3)level3Current++;if(hour.score===3)level3Experimental++;if(rawDelta===0)rawUnchanged++;else if(Math.abs(rawDelta)<=3)rawSmall++;else rawLarge++;if(levelDelta===0){levelUnchanged++;spotSummary[spotId].unchanged++}else if(Math.abs(levelDelta)===1){levelSmall++;spotSummary[spotId].small++}else{levelLarge++;spotSummary[spotId].large++}if(Math.abs(levelDelta)>=2)transitions.push({spotId,hour:index,currentScore:before.score,experimentalScore:hour.score,currentRaw:before.rawScore,experimentalRaw:hour.rawScore})})});
assert.equal(transitions.filter(item=>item.currentScore===0&&item.experimentalScore===3).length,0);assert.ok(level3Experimental<=level3Current+22);assert.ok(comparisons.every(({experimental})=>experimental.hours.every(hour=>hour.experimentalDebug.modelAdjustments.bottom.recentCatchSignals.every(signal=>!String(signal.id).includes('only-pelagic')))));
const jumpCounts={'0->3':0,'1->3':0,'3->1':0,'3->0':0},confidenceAdjustments={low:{count:0,sum:0,max:0},medium:{count:0,sum:0,max:0},high:{count:0,sum:0,max:0}};comparisons.forEach(({current,experimental})=>experimental.hours.forEach((hour,index)=>{const before=current.hours[index],key=`${before.score}->${hour.score}`;if(Object.hasOwn(jumpCounts,key))jumpCounts[key]++;const bucket=confidenceAdjustments[before.confidence]||confidenceAdjustments.low,delta=Math.abs(hour.rawScore-before.rawScore);bucket.count++;bucket.sum+=delta;bucket.max=Math.max(bucket.max,delta)}));Object.values(confidenceAdjustments).forEach(bucket=>{bucket.meanAbsoluteRawDelta=bucket.count?Number((bucket.sum/bucket.count).toFixed(3)):0;delete bucket.sum});
process.stdout.write(JSON.stringify({ok:true,engineVersions:{current:'1.3.0',experimental:MFLForecastExperimental.VERSION,confidence:MFLForecastConfidenceExperimental.VERSION},spots:spotIds.length,modelHours:spotIds.length*24*3,hourComparisons:spotIds.length*24,confidenceAudit,classification:{scoreLevels:{unchanged:levelUnchanged,small:levelSmall,large:levelLarge},rawScores:{unchanged:rawUnchanged,small:rawSmall,large:rawLarge}},spotSummary,level3:{current:level3Current,experimental:level3Experimental,delta:level3Experimental-level3Current},jumpCounts,confidenceAdjustments,largeLevelTransitions:transitions,limits:MFLForecastExperimental.LIMITS,kashimaField:{hours:[15,16,17,18,19].map(hour=>({hour,current:kashima.current.hours[hour].score,experimental:kashima.experimental.hours[hour].score,debug:kashima.experimental.hours[hour].experimentalDebug.modelAdjustments}))}},null,2));
