'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),root=__dirname+'/..';global.window=global;vm.runInThisContext(fs.readFileSync(`${root}/js/forecast/species-presence-shadow.js`,'utf8'),{filename:'species-presence-shadow.js'});
const current={raw:72},copy=JSON.stringify(current),unknown=MFLSpeciesPresenceShadow.calculate({currentRaw:current.raw,presenceScore:.1,reliability:0,preset:'balanced'}),low=MFLSpeciesPresenceShadow.calculate({currentRaw:72,presenceScore:.2,reliability:.2,preset:'balanced'}),high=MFLSpeciesPresenceShadow.calculate({currentRaw:72,presenceScore:.2,reliability:.9,preset:'balanced'});assert.equal(unknown.shadowScore,.72);assert.ok(Math.abs(low.deltaScore)<Math.abs(high.deltaScore));assert.equal(JSON.stringify(current),copy);
const one=MFLSpeciesPresenceShadow.calculate({currentRaw:40,presenceScore:1,reliability:1,preset:'aggressive'});assert.equal(one.shadowScore,.4);assert.equal(one.shadowStars,1);
const stopped=MFLSpeciesPresenceShadow.calculate({currentRaw:90,presenceScore:1,reliability:1,preset:'weighted_blend',safetyStopped:true});assert.equal(stopped.shadowScore,0);assert.equal(stopped.shadowStars,0);
for(const preset of ['conservative','balanced','aggressive','raw_multiplicative','weighted_blend'])assert.ok(MFLSpeciesPresenceShadow.calculate({currentRaw:60,presenceScore:.5,reliability:.5,preset}));
const report=JSON.parse(fs.readFileSync(`${root}/data/species-presence-shadow-report.json`));assert.equal(report.comparableAtSnapshot,180);assert.equal(report.integration.connected,false);assert.equal(report.integration.forecastWeight,0);assert.equal(report.integration.historicalPerformanceWeight,0);assert.equal(report.isolation.productionForecastMutated,false);assert.equal(report.isolation.uiConnected,false);assert.equal(report.isolation.localStorageUsed,false);assert.equal(report.shadowEvaluationsPerPreset,4320);assert.equal(report.experiments.conservative.summary.timeRankChanges,0);assert.equal(report.mappingDistribution.exact+report.mappingDistribution.alias+report.mappingDistribution.variant_group,180);assert.equal(report.mappingDistribution.not_comparable,348);assert.ok(report.experiments.conservative.rows.some(row=>row.potentialMissingDataInflation));
const engine=fs.readFileSync(`${root}/js/forecast/forecast-engine.js`,'utf8'),ui=fs.readFileSync(`${root}/js/forecast/forecast-ui.js`,'utf8'),restrictions=fs.readFileSync(`${root}/js/forecast/forecast-restrictions.js`,'utf8');assert.ok(!engine.includes('MFLSpeciesPresenceShadow'));assert.ok(!ui.includes('MFLSpeciesPresenceShadow'));assert.ok(!restrictions.includes('MFLSpeciesPresenceShadow'));
process.stdout.write(JSON.stringify({ok:true,summary:report.experiments.conservative.summary,readiness:report.readiness},null,2));
