'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),root=__dirname+'/..';global.window=global;
['species-presence-baseline.js','public-environmental-observation.js','species-presence-observation.js','current-forecast-snapshot.js'].forEach(file=>vm.runInThisContext(fs.readFileSync(`${root}/js/forecast/${file}`,'utf8'),{filename:file}));
const read=file=>JSON.parse(fs.readFileSync(`${root}/data/${file}`)),regions=read('marine-regions.json'),profiles=read('species-presence-profiles.json'),sources=read('public-environmental-sources.json'),assignments=read('public-observation-assignments.json'),waterAssignments=read('water-temperature-assignments.json'),tideTable=read('tides-2026.json'),config=read('species-presence-config.json'),nameMapping=read('species-name-mapping.json');
const latest='2026-08-30T06:00:00+09:00',table={'TEST':{lat:[35,36],lon:[140,3]}},map={'TEST':{temp:[27,0],wind:[4,0],windDirection:[8,0],normalPressure:[1010,0],precipitation1h:[0,0]}};
const response=(body,ok=true)=>({ok,status:ok?200:500,text:async()=>typeof body==='string'?body:JSON.stringify(body),json:async()=>body});
const oisst='time,zlev,latitude,longitude,sst\nUTC,m,degrees_north,degrees_east,degree_C\n2026-08-28T12:00:00Z,0.0,35.125,139.875,27.2\n2026-08-28T12:00:00Z,0.0,35.125,140.125,26.8\n2026-08-28T12:00:00Z,0.0,35.625,140.625,26.1\n2026-08-28T12:00:00Z,0.0,35.875,140.875,25.8\n2026-08-28T12:00:00Z,0.0,36.375,140.875,25.2';
const fetchOK=async url=>url.endsWith('latest_time.txt')?response(latest):url.endsWith('amedastable.json')?response(table):url.includes('erddap')?response(oisst):response(map);
(async()=>{
  const collected=await MFLPublicEnvironmentalObservation.collect({fetchImpl:fetchOK,date:'2026-08-30',hour:12,assignments,regions,tideTable,waterAssignments,evaluatedAt:'2026-08-30T12:00:00+09:00'});assert.equal(collected.sourceStatus.jma_amedas_current,'ok');assert.equal(collected.sourceStatus.noaa_oisst_v21_nrt,'ok');assert.equal(collected.productionFallbackUsed,false);assert.equal(Object.keys(collected.environments).length,22);assert.equal(collected.environments.ichihara.waterTemperature,null);assert.equal(collected.environments['kamogawa-coast'].waterTemperature,26.8);assert.equal(collected.environments['kamogawa-coast'].waterTemperatureQuality,'regional_observed');assert.ok(collected.environments.ichihara.sourceIds.includes('jma_amedas_current'));assert.ok(collected.environments.ichihara.sourceIds.includes('jma_tide'));
  const record=collected.recordsBySpot.ichihara[0];['sourceId','provider','observedAt','retrievedAt','latitude','longitude','marineRegion','waterTemp','airTemp','windSpeed','windDirection','pressure','precipitation','waveHeight','wavePeriod','tideLevel','tidePhase','dataQuality','distanceToSpot','isObserved','isRegional','isClimatology'].forEach(field=>assert.ok(Object.hasOwn(record,field),field));assert.equal(record.waterTemp,null);assert.equal(record.waveHeight,null);
  const mismatchRecord=MFLPublicEnvironmentalObservation.normalize({...record,sourceId:'other',marineRegion:'sotobo',waterTemp:20,isObserved:true}),compatibility=MFLPublicEnvironmentalObservation.compatible(mismatchRecord,assignments.spots.ichihara,'tokyo_bay_central');assert.equal(compatibility.accepted,false);assert.equal(compatibility.quality,'low');
  assert.equal(MFLPublicEnvironmentalObservation.classifyDepth(1.2),'surface');assert.equal(MFLPublicEnvironmentalObservation.classifyDepth(7),'subsurface');assert.equal(MFLPublicEnvironmentalObservation.classifyDepth(18),'bottom');assert.equal(MFLPublicEnvironmentalObservation.classifyDepth(null),'unknown');
  const coastal=MFLPublicEnvironmentalObservation.normalize({sourceId:'official_coastal',observedAt:'2026-08-30T10:00:00+09:00',retrievedAt:'2026-08-30T11:00:00+09:00',latitude:35.55,longitude:140.02,marineRegion:'tokyo_bay_central',waterTemp:28.1,isObserved:true,observationDepth:1.5,coastSide:'chiba',bayZone:'central'}),coastalRule={enabled:true,marineRegion:'tokyo_bay_central',coastSide:'chiba',bayZone:'central',maxAgeHours:48};assert.equal(coastal.depthClass,'surface');assert.equal(MFLPublicEnvironmentalObservation.coastalCompatibility(coastal,assignments.spots.ichihara,coastalRule,'2026-08-30T12:00:00+09:00').accepted,true);assert.equal(MFLPublicEnvironmentalObservation.coastalCompatibility(coastal,assignments.spots.edogawa_hosuiro,coastalRule,'2026-08-30T12:00:00+09:00').reason,'estuary_requires_dedicated_observation');assert.equal(MFLPublicEnvironmentalObservation.coastalCompatibility(coastal,assignments.spots.ichihara,{...coastalRule,coastSide:'kanagawa'},'2026-08-30T12:00:00+09:00').reason,'coast_side_mismatch');assert.equal(MFLPublicEnvironmentalObservation.coastalCompatibility({...coastal,depthClass:'bottom'},assignments.spots.ichihara,coastalRule,'2026-08-30T12:00:00+09:00').reason,'depth_not_suitable');assert.equal(MFLPublicEnvironmentalObservation.coastalCompatibility(coastal,assignments.spots.ichihara,{...coastalRule,enabled:false,reason:'license_restricted'},'2026-08-30T12:00:00+09:00').reason,'license_restricted');
  const crossCheck=MFLPublicEnvironmentalObservation.crossCheckWaterTemperature(coastal,{value:27.2,sourceId:'noaa_oisst_v21_nrt'});assert.equal(crossCheck.difference,.9);assert.equal(crossCheck.coastalDepthClass,'surface');
  const batch=MFLSpeciesPresenceObservation.evaluateAll({date:'2026-08-30',environments:collected.environments,regions,profiles,sources,config}),expectedEvaluations=22*Object.keys(profiles.species).length;assert.equal(batch.spotCount,22);assert.equal(batch.speciesCount,24);assert.equal(batch.evaluationCount,expectedEvaluations);assert.equal(batch.integration.connected,false);assert.equal(batch.integration.forecastWeight,0);assert.equal(batch.integration.historicalPerformanceWeight,0);assert.ok(batch.results.every(item=>item.environmentalSourceIds.includes('jma_amedas_current')));assert.ok(batch.details.filter(item=>item.waterTemperature.quality==='missing').every(item=>item.dataConfidence.level!=='high'&&item.missingCriticalInputs.includes('waterTemperature')));
  const detail=(spotId,speciesId)=>batch.details.find(item=>item.spotId===spotId&&item.speciesId===speciesId);assert.equal(detail('asahi-ioka-coast','kasago').habitatMatch.status,'mismatch');assert.equal(detail('hiraiso','kasago').habitatMatch.status,'match');assert.ok(detail('hiraiso','kasago').scores.regionScore>detail('asahi-ioka-coast','kasago').scores.regionScore);assert.equal(detail('hiraiso','kisu').habitatMatch.status,'mismatch');assert.ok(detail('hiraiso','kisu').score<.66);assert.equal(detail('asahi-ioka-coast','kisu').habitatMatch.status,'match');assert.equal(detail('choshi-nagasaki-coast','mahaze').marineRegionMatch,false);assert.ok(detail('choshi-nagasaki-coast','mahaze').score<=.45);assert.equal(detail('asahi-ioka-coast','hirame').habitatMatch.status,'match');assert.equal(detail('asahi-ioka-coast','magochi').habitatMatch.status,'match');assert.equal(detail('kemigawa_beach','buri').marineRegionMatch,false);assert.ok(detail('kemigawa_beach','buri').score<=.45);
  const existing={ichihara:{aji:3,kisu:1}},comparisons=MFLSpeciesPresenceObservation.compareAll({batch,existingForecasts:existing,profiles});assert.equal(comparisons.length,expectedEvaluations);assert.equal(comparisons.find(item=>item.speciesPresenceBaseline.spotId==='ichihara'&&item.speciesPresenceBaseline.speciesId==='aji').summary.existingForecast,'★★★');const mismatches=MFLSpeciesPresenceObservation.findMismatches({comparisons,config});assert.ok(Array.isArray(mismatches));
  const mismatchFixture=[
    {existingForecast:{score:3},speciesPresenceBaseline:{spotId:'a',speciesId:'a',score:.3,label:'低',scores:{seasonScore:.2,waterTempScore:.2},dataConfidence:{level:'medium'}}},
    {existingForecast:{score:1},speciesPresenceBaseline:{spotId:'b',speciesId:'b',score:.8,label:'高',scores:{seasonScore:.8,waterTempScore:.8},dataConfidence:{level:'medium'}}},
    {existingForecast:null,speciesPresenceBaseline:{spotId:'c',speciesId:'c',score:.5,label:'中',scores:{seasonScore:1,waterTempScore:.1},dataConfidence:{level:'medium'}}},
    {existingForecast:null,speciesPresenceBaseline:{spotId:'d',speciesId:'d',score:.8,label:'高',scores:{seasonScore:.8,waterTempScore:null},dataConfidence:{level:'low'}}}
  ],mismatchTypes=MFLSpeciesPresenceObservation.findMismatches({comparisons:mismatchFixture,config}).flatMap(item=>item.reasons);['existing_high_presence_low','existing_low_presence_high','season_water_conflict','high_score_low_confidence'].forEach(type=>assert.ok(mismatchTypes.includes(type),type));
  const failed=await MFLPublicEnvironmentalObservation.collect({fetchImpl:async()=>response('',false),date:'2026-08-30',hour:12,assignments,regions,tideTable,waterAssignments});assert.equal(failed.sourceStatus.jma_amedas_current,'failed');assert.equal(failed.sourceStatus.noaa_oisst_v21_nrt,'failed');assert.equal(failed.productionFallbackUsed,false);assert.equal(Object.keys(failed.environments).length,22);assert.ok(failed.environments.ichihara.sourceIds.includes('jma_tide'));assert.equal(failed.environments.ichihara.waterTemperature,null);
  const oldDataset={records:MFLPublicEnvironmentalObservation.parseOisstCsv(oisst,'2026-08-30T00:00:00Z')},oldWater=MFLPublicEnvironmentalObservation.waterTemperatureForSpot({spotId:'kamogawa-coast',spot:assignments.spots['kamogawa-coast'],regionId:'sotobo',dataset:oldDataset,assignments:waterAssignments,evaluatedAt:'2026-09-15T00:00:00+09:00'});assert.equal(oldWater.quality,'missing');assert.equal(oldWater.reason,'observation_expired');
  assert.deepEqual(MFLPublicEnvironmentalObservation.jstParts('2026-08-30T15:30:00Z'),{date:'2026-08-31',hour:0});assert.deepEqual(MFLPublicEnvironmentalObservation.jstParts('2026-08-31T00:30:00+09:00'),{date:'2026-08-31',hour:0});
  const spotProfile={speciesGroups:{pelagic:{species:['アジ','マイワシ']},bottom:{species:['シロギス']},other:{species:['スズキ']}}},existingResult={hours:Array.from({length:24},()=>({models:{pelagic:{score:3},bottom:{score:2},other:{score:1}}}))},snapshot=MFLCurrentForecastSnapshot.build({date:'2026-08-30',hour:12,spotResults:{ichihara:{result:existingResult,spotProfile}},nameMapping});assert.equal(snapshot.readOnly,true);assert.equal(snapshot.spots.ichihara.aji.existingForecastScore,3);assert.equal(snapshot.spots.ichihara.iwashi.existingForecastScore,3);assert.equal(snapshot.spots.ichihara.mahaze.comparisonStatus,'not_comparable');const comparisonRecords=MFLSpeciesPresenceObservation.comparisonRecords({batch,snapshot});assert.equal(comparisonRecords.length,expectedEvaluations);assert.ok(['comparable','not_comparable'].includes(comparisonRecords[0].comparisonStatus));assert.ok(comparisonRecords.every(item=>Object.hasOwn(item,'habitatMatch')&&Object.hasOwn(item,'marineRegionMatch')));
  ['forecast-engine.js','forecast-features.js','forecast-ui.js','forecast-restrictions.js','forecast-data.js'].forEach(file=>{const code=fs.readFileSync(`${root}/js/forecast/${file}`,'utf8');assert.ok(!code.includes('species-presence-observation'));assert.ok(!code.includes('public-environmental-observation'))});assert.equal(sources.policy.predictionWeight,0);assert.equal(config.forecastWeight,0);assert.equal(config.historicalPerformanceWeight,0);
  process.stdout.write(JSON.stringify({ok:true,sourceStatus:collected.sourceStatus,evaluationCount:batch.evaluationCount,mismatchCount:mismatches.length,failedSourceStatus:failed.sourceStatus},null,2));
})().catch(error=>{console.error(error);process.exitCode=1});
