'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),root=__dirname+'/..';global.window=global;
vm.runInThisContext(fs.readFileSync(`${root}/js/forecast/species-presence-shadow-analysis.js`,'utf8'),{filename:'species-presence-shadow-analysis.js'});
const makeRow=(hour,currentRaw,presenceScore,reliability,currentScore,shadowScore,delta,state='available')=>({hour,current:{score:currentScore,rawScore:currentRaw},presence:{state,usable:state==='available',score:presenceScore,reliability},shadow:{score:shadowScore,rawScore:currentRaw+delta},delta:{raw:delta,score:shadowScore-currentScore,direction:delta>0?'up':delta<0?'down':'unchanged'},shadowStatus:state==='available'?'calculated':'current_fallback'});
const report={phase:'7-shadow-integration',date:'2026-08-30',generatedAt:'fixture',coverage:{comparisons:2},summary:{bestHoursChanged:0},comparisons:[{spotId:'a',speciesId:'aji',group:'pelagic',date:'2026-08-30',presence:{score:.9,reliability:{value:.8},hardGateEligible:true,sourceIds:['official'],missingCriticalInputs:[]},rows:[makeRow(5,30,.9,.8,1,2,5.8),makeRow(6,95,.9,.8,3,3,-.5)]},{spotId:'b',speciesId:'kisu',group:'bottom',date:'2026-08-30',presence:{score:.7,reliability:{value:.3},hardGateEligible:false,sourceIds:[],missingCriticalInputs:['waterTemperature']},rows:[makeRow(5,40,.7,.3,1,1,0,'indeterminate'),makeRow(6,50,.7,.3,2,2,0,'indeterminate')]}]};
const result=MFLSpeciesPresenceShadowAnalysis.analyze(report,{performanceRecords:{records:[]}});
assert.equal(result.fixedParameters.blendStrength,.12);assert.equal(result.fixedParameters.maxRawDelta,8);assert.equal(result.fixedParameters.changed,false);
assert.equal(result.overall.available,2);assert.equal(result.fallback.total,2);assert.equal(result.scoreTransitions.total,1);assert.equal(result.scoreTransitions.counts['1->2'],1);
assert.equal(result.fallback.reasons.indeterminate_missing_critical_inputs.count,2);assert.equal(result.empiricalValidation.status,'INSUFFICIENT_DATA');assert.equal(result.empiricalValidation.claimImprovedAccuracy,false);
assert.equal(result.productionSafety.currentChanged,false);assert.equal(result.productionSafety.uiConnected,false);assert.ok(result.clamp.maxTheoreticalPositive>5);
const productionFiles=['forecast-engine.js','forecast-features.js','forecast-ui.js','forecast-data.js'];for(const file of productionFiles){const code=fs.readFileSync(`${root}/js/forecast/${file}`,'utf8');assert.ok(!code.includes('MFLSpeciesPresenceShadowAnalysis'))}
process.stdout.write(JSON.stringify({ok:true,version:MFLSpeciesPresenceShadowAnalysis.VERSION,available:result.overall.available,fallback:result.fallback.total,scoreChanges:result.scoreTransitions.total},null,2));
