'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto'),root=__dirname+'/..';global.window=global;
for(const file of['species-presence-shadow-runner.js','species-presence-integration-experiment.js','species-presence-timefactor-experiment.js','species-presence-cm-multiday.js'])vm.runInThisContext(fs.readFileSync(`${root}/js/forecast/${file}`,'utf8'),{filename:file});
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(`${root}/${file}`)).digest('hex'),protectedFiles=['js/forecast/forecast-engine.js','js/forecast/forecast-features.js','data/fishing-forecast-baselines.json','data/fishing-forecast-spots.json','js/tides.js'],before=Object.fromEntries(protectedFiles.map(file=>[file,hash(file)]));
function rows(seed=0,safe=true){return Array.from({length:24},(_,hour)=>{const raw=20+((hour+seed)%12)*5,current={raw,score:raw>=72?3:raw>=50?2:raw>=30?1:0,recommended:safe},presence={usable:true,score:.7,reliability:.6},sourceRow={hour,current:{rawScore:raw,score:current.score,recommended:safe},presence,shadowStatus:safe?'calculated':'safety_passthrough'},cm=MFLSpeciesPresenceTimeFactorExperiment.method(sourceRow,'CM');return{hour,current,presence,cm}})}
function day(date,classification='real_observation',seed=0){return{date,classification,conditions:{weekend:false},currentStatus:{complete:true},presenceStatus:{available:1},currentRows:24,presenceRows:1,comparisons:[{spotId:'test',speciesId:'aji',group:'pelagic',rows:rows(seed)}],fallbackReasons:{}}}
const dataset={spotCount:22,currentMutated:false,uiConnected:false,days:[day('2026-08-30','real_observation',0),day('2026-08-31','real_observation',1),day('2026-09-01','real_observation',2),day('fixture','fixture',3)]},input=JSON.stringify(dataset),report=MFLSpeciesPresenceCMMultiday.analyze(dataset),again=MFLSpeciesPresenceCMMultiday.analyze(dataset);
assert.equal(JSON.stringify(dataset),input);assert.equal(report.classifications.realObservation.count,3);assert.equal(report.classifications.fixture.count,1);assert.equal(report.coverage.comparisonRows,72);assert.equal(report.inputUnchanged,true);assert.deepEqual(report.daily.map(item=>item.date),['2026-08-30','2026-08-31','2026-09-01']);assert.equal(report.anomalies.invalidNumeric,0);assert.equal(report.anomalies.largeJumps,0);assert.equal(report.anomalies.safetyBroken,0);assert.equal(report.assessment.productionIntegration,'HOLD');assert.equal(report.assessment.accuracyEvaluated,false);assert.equal(JSON.stringify({...report,generatedAt:null}),JSON.stringify({...again,generatedAt:null}));
const safetyDay=day('2026-09-02','real_observation');safetyDay.comparisons[0].rows=rows(0,false);const safetyReport=MFLSpeciesPresenceCMMultiday.analyze({spotCount:22,currentMutated:false,uiConnected:false,days:[safetyDay,safetyDay,safetyDay]});assert.equal(safetyReport.anomalies.safetyBroken,0);
assert.deepEqual(Object.fromEntries(protectedFiles.map(file=>[file,hash(file)])),before);for(const file of['forecast-engine.js','forecast-features.js','forecast-ui.js','forecast-data.js'])assert.ok(!fs.readFileSync(`${root}/js/forecast/${file}`,'utf8').includes('MFLSpeciesPresenceCMMultiday'));
const reportPath=`${root}/data/species-presence-cm-multiday-phase12-report.json`;if(fs.existsSync(reportPath)){const saved=JSON.parse(fs.readFileSync(reportPath));assert.equal(saved.schemaVersion,'1.0.0');assert.equal(saved.phase,'12-cm-multiday-stability');assert.ok(saved.classifications.realObservation.count>=3);assert.equal(saved.anomalies.invalidNumeric,0);assert.equal(saved.anomalies.largeJumps,0);assert.equal(saved.anomalies.safetyBroken,0);assert.equal(saved.assessment.productionIntegration,'HOLD')}
process.stdout.write(JSON.stringify({ok:true,version:MFLSpeciesPresenceCMMultiday.VERSION,classification:report.classifications,assessment:report.assessment},null,2));
