'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),root=__dirname+'/..';global.window=global;vm.runInThisContext(fs.readFileSync(`${root}/js/forecast/species-presence-shadow-runner.js`,'utf8'),{filename:'species-presence-shadow-runner.js'});
const makeCurrent=(date,spotId)=>({engineVersion:'1.3.0',date,spotId,hours:Array.from({length:24},(_,hour)=>({hour,score:hour>=17&&hour<=19?3:hour>=5&&hour<=7?2:1,rawScore:hour>=17&&hour<=19?78:hour>=5&&hour<=7?62:38,confidence:hour%2?'medium':'low',reasons:[hour>=17&&hour<=19?'夕マヅメ':'季節傾向'],dominantGroup:hour>=12?'pelagic':'bottom',recommended:true,recommendedMethod:hour>=12?'サビキ':'ちょい投げ',targetSpecies:hour>=12?['アジ']:['シロギス']}))});
(async()=>{
  const cases=[['kashima','2026-08-30'],['kemigawa_beach','2026-09-01'],['ichihara','2026-09-02']],comparisons=[];
  for(const [spotId,date] of cases){const current=makeCurrent(date,spotId),before=JSON.stringify(current),result=await MFLSpeciesPresenceShadowRunner.compare24({spotId,date,currentResult:current,presenceByGroup:{pelagic:{score:.9,reliability:{value:.8},label:'存在しやすい'},bottom:{score:.25,reliability:{value:.7},label:'存在条件弱め'}}});assert.equal(result.rows.length,24);assert.equal(result.currentUnchanged,true);assert.equal(JSON.stringify(current),before);assert.ok(result.summary.up>0);assert.ok(result.summary.down>0);assert.ok(result.rows.every(row=>Math.abs(row.delta.raw)<=8));assert.ok(result.rows.every(row=>row.current.confidence&&row.current.reasons.length));comparisons.push(result)}
  const current=makeCurrent('2026-09-03','urayasu_chidori'),absent=await MFLSpeciesPresenceShadowRunner.compare24({spotId:'urayasu_chidori',date:'2026-09-03',currentResult:current,presenceByGroup:{}});assert.equal(absent.summary.unchanged,24);assert.ok(absent.rows.every(row=>row.shadowStatus==='current_fallback'));
  for(const invalid of [null,'bad',{score:null,reliability:1},{score:2,reliability:1},{score:.5,reliability:-1},{score:.5,reliability:.8,hardGateEligible:false}]){const result=await MFLSpeciesPresenceShadowRunner.compare24({spotId:'kashima',date:'2026-09-04',currentResult:current,presenceByGroup:{pelagic:invalid,bottom:invalid}});assert.equal(result.summary.unchanged,24);assert.ok(result.rows.every(row=>row.delta.raw===0))}
  const failed=await MFLSpeciesPresenceShadowRunner.compare24({spotId:'kashima',date:'2026-09-05',currentResult:current,loadPresence:async()=>{throw new Error('fixture load failure')}});assert.equal(failed.presenceStatus,'load_failed');assert.equal(failed.summary.unchanged,24);assert.equal(failed.currentUnchanged,true);
  const unsafe=makeCurrent('2026-09-05','kashima');unsafe.hours[18].recommended=false;unsafe.hours[18].score=0;unsafe.hours[18].rawScore=0;const safe=await MFLSpeciesPresenceShadowRunner.compare24({spotId:'kashima',date:'2026-09-05',currentResult:unsafe,presenceByGroup:{pelagic:{score:1,reliability:1}}});assert.equal(safe.rows[18].shadowStatus,'safety_passthrough');assert.equal(safe.rows[18].shadow.score,0);
  const malformedCurrent=await MFLSpeciesPresenceShadowRunner.compare24({spotId:'bad',date:'2026-09-05',currentResult:{hours:[]},presenceByGroup:{}});assert.equal(malformedCurrent.shadowStatus,'failed');
  const log=MFLSpeciesPresenceShadowRunner.humanLog(comparisons[0]);assert.equal(log.length,24);assert.ok(log[18].includes('CURRENT')&&log[18].includes('SHADOW'));
  const productionFiles=['forecast-engine.js','forecast-features.js','forecast-ui.js','forecast-data.js'];for(const file of productionFiles){const code=fs.readFileSync(`${root}/js/forecast/${file}`,'utf8');assert.ok(!code.includes('MFLSpeciesPresenceShadowRunner'))}
  const reportPath=`${root}/data/species-presence-shadow-phase7-report.json`;if(fs.existsSync(reportPath)){const report=JSON.parse(fs.readFileSync(reportPath));assert.equal(report.mode,'shadow_only');assert.equal(report.current.engineVersion,'1.3.0');assert.equal(report.current.mutated,false);assert.equal(report.shadow.writeBack,false);assert.equal(report.shadow.uiConnected,false);assert.equal(report.shadow.localStorageUsed,false);assert.equal(report.coverage.hourRows,report.coverage.comparisons*24);assert.ok(report.summary.maxAbsRawDelta<=8);assert.equal(report.readiness.productionAdoption,false)}
  process.stdout.write(JSON.stringify({ok:true,version:MFLSpeciesPresenceShadowRunner.VERSION,spots:cases.length,dates:new Set(cases.map(item=>item[1])).size,presence:{available:{up:comparisons[0].summary.up,down:comparisons[0].summary.down,unchanged:comparisons[0].summary.unchanged},absent:absent.summary,loadFailure:failed.summary},maxRawDelta:MFLSpeciesPresenceShadowRunner.MAX_RAW_DELTA,currentUnchanged:comparisons.every(item=>item.currentUnchanged),uiConnected:false},null,2));
})().catch(error=>{console.error(error);process.exitCode=1});
