'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),root=__dirname+'/..';global.window=global;
for(const file of ['species-presence-baseline.js','species-presence-model-audit.js'])vm.runInThisContext(fs.readFileSync(`${root}/js/forecast/${file}`,'utf8'),{filename:file});
const regions=JSON.parse(fs.readFileSync(`${root}/data/marine-regions.json`)),profiles=JSON.parse(fs.readFileSync(`${root}/data/species-presence-profiles.json`)),sources=JSON.parse(fs.readFileSync(`${root}/data/public-environmental-sources.json`)),report=JSON.parse(fs.readFileSync(`${root}/data/species-presence-observation-report.json`)),ledger=JSON.parse(fs.readFileSync(`${root}/data/species-presence-feature-overlap.json`));
const environment={waterTemperature:24,waterTemperatureQuality:'observed',observationDate:'2026-08-30',evaluatedAt:'2026-08-30',waveHeight:.5,windSpeed:3,tidePhase:'rising'};
const evaluate=(speciesId='aji',overrides={})=>MFLSpeciesPresenceBaseline.evaluate({spotId:'ichihara',speciesId,date:'2026-08-30',environment,observations:[],regions,profiles,sources,...overrides});

const ordinary=evaluate();
for(const component of ['speciesProfileConfidence','environmentDataConfidence','spatialMatchConfidence','temporalFreshnessConfidence','overallDataConfidence'])assert.ok(ordinary.dataConfidence[component],`missing ${component}`);
const weak=evaluate('ainame');assert.equal(weak.dataConfidence.speciesProfileConfidence.level,'low');assert.notEqual(weak.dataConfidence.overallDataConfidence.level,'high');
const missing=evaluate('aji',{environment:{evaluatedAt:'2026-08-30'},observations:[]});assert.equal(missing.waterTemperature.quality,'missing');assert.notEqual(missing.dataConfidence.overallDataConfidence.level,'high');assert.ok(missing.missingCriticalInputs.includes('waterTemperature'));

const highProfiles=JSON.parse(JSON.stringify(profiles)),lowProfiles=JSON.parse(JSON.stringify(profiles));highProfiles.species.aji.sourceQuality='high';lowProfiles.species.aji.sourceQuality='low';
const highProfile=evaluate('aji',{profiles:highProfiles}),lowProfile=evaluate('aji',{profiles:lowProfiles});assert.equal(highProfile.score,lowProfile.score);assert.notEqual(highProfile.dataConfidence.level,lowProfile.dataConfidence.level);

const both=evaluate('hirame',{spotId:'edogawa_hosuiro',environment:{evaluatedAt:'2026-08-30'},observations:[]});assert.ok(both.structuralCompatibility.capType.includes('marine_region'));assert.ok(both.structuralCompatibility.capType.includes('habitat'));assert.equal(both.structuralCompatibility.capValue,.45);assert.equal(both.structuralCompatibility.finalPresenceScore,both.score);assert.ok(both.structuralCompatibility.rawPresenceScore>=both.structuralCompatibility.finalPresenceScore);
assert.equal(Math.min(.45,.65),Math.min(.65,.45));

const calm=evaluate('aji',{environment:{waterTemperature:24,waterTemperatureQuality:'observed',observationDate:'2026-08-30',evaluatedAt:'2026-08-30',waveHeight:.1,windSpeed:1,tidePhase:'rising',weatherCode:0,pressure:1020,precipitation:0,hour:5}}),rough=evaluate('aji',{environment:{waterTemperature:24,waterTemperatureQuality:'observed',observationDate:'2026-08-30',evaluatedAt:'2026-08-30',waveHeight:8,windSpeed:30,tidePhase:'falling',weatherCode:99,pressure:970,precipitation:80,hour:15}});assert.equal(calm.score,rough.score);assert.equal(calm.scoreFeatures.shortTermBiteability.usedForPresenceScore,false);assert.equal(calm.weights.marineCondition,0);
const winter=evaluate('aji',{date:'2026-01-30'});assert.notEqual(ordinary.score,winter.score);assert.notEqual(hotAjiScore(),ordinary.score);
function hotAjiScore(){return evaluate('aji',{environment:{waterTemperature:34,waterTemperatureQuality:'observed',observationDate:'2026-08-30',evaluatedAt:'2026-08-30'}}).score}
assert.ok(ordinary.presenceReliability);assert.equal(typeof ordinary.hardGateEligible,'boolean');assert.equal(missing.hardGateEligible,false);assert.equal(weak.hardGateEligible,false);
const audit=report.phase65.modelAudit;assert.equal(audit.evaluationCount,528);assert.equal(audit.scoreDistribution.histogram.reduce((sum,item)=>sum+item.count,0),528);assert.equal(audit.missing.waterTemperatureMissing.count,216);assert.ok(audit.missing.potentialMissingDataInflation.count>0);assert.equal(audit.caps.orderIndependent,true);
assert.equal(ledger.features.filter(item=>item.overlap==='must_separate_before_integration').length,0);for(const name of ['tidePhase/presence','windSpeed','waveHeight']){const feature=ledger.features.find(item=>item.feature===name);assert.equal(feature.usedByPresenceBaseline,false);assert.equal(feature.presenceWeight,0)}assert.equal(report.phase65.profileLowGroups[0].evaluationCount,22);assert.equal(report.phase65.scoreChanges.length,528);assert.equal(report.phase65.readiness.status,'READY');assert.equal(report.integration.connected,false);assert.equal(report.integration.forecastWeight,0);assert.equal(report.integration.historicalPerformanceWeight,0);
const productionFiles=['forecast-engine.js','forecast-features.js','forecast-ui.js','forecast-data.js'];for(const file of productionFiles)assert.ok(!fs.readFileSync(`${root}/js/forecast/${file}`,'utf8').includes('speciesPresenceBaseline'));
process.stdout.write(JSON.stringify({ok:true,confidence:audit.confidence,caps:audit.caps,missing:audit.missing.potentialMissingDataInflation.count},null,2));
