/* MFL fishing expectation UI v1.7.3 (forecast engine v1.3) */
(function(){
  'use strict';
  const supported=new Set(['kashima','kemigawa_beach','ichihara','kisarazu_uchiko','futtsu_area','urayasu_chidori','edogawa_hosuiro','tateyama_sunset','choshi-marina-coast','choshi-nagasaki-coast','asahi-ioka-coast','onjuku-coast','kamogawa-coast','kawarago','hiraiso','honmoku','isogo','daikoku','higashiogishima','umibetsuri','umikaze','aicle']),forecastPrefectures=['千葉','茨城','神奈川'],confidenceLabel={low:'低',medium:'中',high:'高'},displayNames={kashima:'鹿島港魚釣園',kemigawa_beach:'検見川浜',ichihara:'市原海づり施設',kisarazu_uchiko:'木更津内港公園',futtsu_area:'富津地区',urayasu_chidori:'浦安千鳥',edogawa_hosuiro:'江戸川放水路',tateyama_sunset:'館山夕日桟橋','choshi-marina-coast':'銚子マリーナ・名洗','choshi-nagasaki-coast':'長崎海岸','asahi-ioka-coast':'飯岡・旭海岸','onjuku-coast':'御宿海岸','kamogawa-coast':'鴨川・前原海岸',kawarago:'河原子海岸',hiraiso:'平磯周辺の岩場',honmoku:'本牧海づり施設',isogo:'磯子海づり施設',daikoku:'大黒海づり施設',higashiogishima:'東扇島西公園',umibetsuri:'海辺つり公園',umikaze:'うみかぜ公園',aicle:'アイクル海釣りコーナー'};
  const weatherLabels={0:'快晴',1:'晴れ',2:'一部くもり',3:'くもり',45:'霧',48:'霧',51:'弱い雨',53:'雨',55:'雨',61:'雨',63:'雨',65:'強い雨',71:'雪',80:'にわか雨',81:'にわか雨',82:'強い雨',95:'雷雨'};
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,value)),fishIcons=score=>score===null?'—':score===0?'<span class="forecast-faint-fish">🐟</span>':'🐟'.repeat(score);
  const hourLabel=hour=>`${hour}時`,windowLabel=item=>item.startHour===item.endHour?hourLabel(item.startHour):`${item.startHour}〜${item.endHour}時`,modelLevel=model=>model?.score===null?'未算出':model.score>=3?'高':model.score===2?'中':model.score===1?'低':'期待薄';
  const tokyoParts=(date=new Date())=>Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date).map(x=>[x.type,x.value]));
  const localDate=date=>{const parts=tokyoParts(date);return`${parts.year}-${parts.month}-${parts.day}`};
  const localHour=date=>Number(tokyoParts(date).hour);
  const localTime=date=>{const parts=tokyoParts(date);return Number(parts.hour)+Number(parts.minute)/60};
  const displayDate=value=>value?value.replace(/-/g,'/'):'—',latestEvidence=baseline=>Object.values(baseline.models||{}).flatMap(model=>Object.values(model.season||{}).map(season=>season.evidence?.lastUpdated).filter(Boolean)).sort().at(-1)||'',isTodayResult=result=>result.hours[0]?.feature.date===localDate();
  function allWindows(result){const windows=[];let current=null;result.hours.filter(item=>item.score!==null&&item.recommended&&item.score>=1).forEach(item=>{const joins=current&&item.hour===current.endHour+1&&item.score===current.score&&item.dominantGroup===current.dominantGroup&&item.recommendedMethod===current.recommendedMethod;if(!joins){current={startHour:item.hour,endHour:item.hour,score:item.score,rawScore:item.rawScore,dominantGroup:item.dominantGroup,recommendedMethod:item.recommendedMethod,targetSpecies:item.targetSpecies,hours:[item.hour]};windows.push(current)}else{current.endHour=item.hour;current.hours.push(item.hour);current.rawScore=Math.max(current.rawScore,item.rawScore)}});return windows}
  const blockingRestriction=(result,hour)=>result.hours.find(item=>item.hour===hour)?.feature?.safety?.restriction?.blocking?.[0]||null;
  function wholeDayRestriction(result){
    if(result.hours.length!==24)return null;
    const restrictions=result.hours.map(item=>(item.feature?.safety?.restriction?.blocking||[]).find(restriction=>restriction.type==='full_day'&&restriction.scope==='whole_spot'));
    return restrictions.every(Boolean)?restrictions[0]:null
  }
  function relevantWindows(result,nowHour=localHour()){const windows=allWindows(result);if(!isTodayResult(result))return windows.sort((a,b)=>b.rawScore-a.rawScore||a.startHour-b.startHour).slice(0,3);return windows.filter(item=>item.endHour>=nowHour).sort((a,b)=>b.rawScore-a.rawScore||a.startHour-b.startHour).slice(0,3)}
  function deriveOverview(result,nowHour=localHour()){const today=isTodayResult(result),hours=result.hours.filter(item=>item.score!==null&&item.recommended&&(!today||item.hour>=nowHour)),windows=relevantWindows(result,nowHour),restriction=today?blockingRestriction(result,nowHour):null;if(!hours.length||!windows.length)return{score:0,label:restriction?.label||(today?'本日の主な時合いは終了':'狙い目なし'),method:'—',confidence:result.confidence||'low',windows:[],restriction};const best=windows[0],duration=best.endHour-best.startHour+1,sustained=hours.filter(item=>item.score>=2).length,impact=best.score*Math.min(duration,3)/3+(sustained>=4?.5:sustained>=2?.25:0);return{score:clamp(Math.round(impact),1,3),label:windowLabel(best),method:best.recommendedMethod||'—',confidence:result.confidence||'low',windows}}
  function fishStack(score){if(score===null)return'<span class="forecast-unknown">—</span>';if(score===0)return'<span class="forecast-zero"></span>';return`<span class="forecast-fish-stack">${Array.from({length:score},()=>'<i>🐟</i>').join('')}</span>`}
  function solarTimes(result){const feature=result.hours[0]?.feature||{},valid=value=>Number.isFinite(value)&&value>=0&&value<24;return{sunrise:valid(feature.sunrise)?feature.sunrise:5.5,sunset:valid(feature.sunset)?feature.sunset:18,fallback:!valid(feature.sunrise)||!valid(feature.sunset)}}
  function sameRun(a,b){return Boolean(a&&b&&a.score===b.score&&a.dominantGroup===b.dominantGroup&&a.recommendedMethod===b.recommendedMethod)}
  function daypartHTML(result){const {sunrise,sunset}=solarTimes(result),dawnStart=clamp(sunrise-1.5,0,24),dawnEnd=clamp(sunrise+1.5,0,24),duskStart=clamp(sunset-1.5,0,24),duskEnd=clamp(sunset+1.5,0,24),parts=[['late-night',0,dawnStart],['dawn',dawnStart,dawnEnd],['day',dawnEnd,duskStart],['dusk',duskStart,duskEnd],['night',duskEnd,24]];return`<div class="forecast-dayparts" aria-hidden="true">${parts.filter(part=>part[2]>part[1]).map(part=>`<i class="${part[0]}" style="left:${(part[1]/24*100).toFixed(2)}%;width:${((part[2]-part[1])/24*100).toFixed(2)}%"></i>`).join('')}</div>`}
  function solarMarkersHTML(result,scope,nowHour=null,eventXs=[]){const solar=solarTimes(result),items=[{type:'sunrise',hour:solar.sunrise,icon:'🌅',label:'日の出'},{type:'sunset',hour:solar.sunset,icon:'🌇',label:'日の入'}];return items.map(item=>{const x=clamp(item.hour/23*100,0,100),nearNow=scope==='tide'&&nowHour!==null&&Math.abs(item.hour-nowHour)<1?' near-now':'',nearEvent=scope==='tide'&&eventXs.some(eventX=>Math.abs(eventX-x)<11)?' near-event':'';return`<span class="forecast-solar-marker ${scope} ${item.type}${nearNow}${nearEvent}" style="left:${x.toFixed(2)}%" title="${item.label} ${formatHour(item.hour)}"><b>${item.icon}</b><small>${scope==='chart'?'':item.label}</small></span>`}).join('')}
  function formatHour(value){const hour=Math.floor(value),minute=Math.round((value-hour)*60);return`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`}
  function graphHTML(result){const prohibited=wholeDayRestriction(result);if(prohibited)return`<div class="forecast-chart forecast-chart-prohibited" role="img" aria-label="本日は終日釣り禁止"><div><span aria-hidden="true">🚫</span><strong>本日は釣り禁止</strong><small>${prohibited.reason||'利用制限により時間別の期待度を表示していません。'}</small></div></div>`;const nowHour=localHour(),today=isTodayResult(result),major=new Set([0,3,6,9,12,15,18,21,23]),primary=primaryWindow(result,nowHour);return`<div class="forecast-chart" aria-label="0時から23時の釣果期待度グラフ">${daypartHTML(result)}${solarMarkersHTML(result,'chart')}<div class="forecast-chart-hours">${result.hours.map((item,index)=>{const previous=result.hours[index-1],next=result.hours[index+1],joinPrev=sameRun(previous,item),joinNext=sameRun(item,next),runClass=joinPrev&&joinNext?' run-mid':joinPrev?' run-end':joinNext?' run-start':' run-single',isPrimary=primary&&item.hour>=primary.startHour&&item.hour<=primary.endHour;return`<button type="button" class="forecast-chart-hour level-${item.score===null?'unknown':item.score}${runClass}${isPrimary?' primary-range':''}${today&&item.hour===nowHour?' current':''}${item.recommended?'':' unsafe'}" data-forecast-hour="${item.hour}" aria-label="${item.hour}時、期待度${item.score===null?'未算出':item.score}、${item.recommendedMethod||'おすすめなし'}${today&&item.hour===nowHour?'、現在時刻':''}"><span class="forecast-chart-fish">${fishStack(item.score)}</span><small class="${major.has(item.hour)?'major':''}">${major.has(item.hour)?item.hour:''}</small>${today&&item.hour===nowHour?'<u>今</u>':''}</button>`}).join('')}</div><div class="forecast-chart-axis" aria-hidden="true"></div></div>`}
  function bestHour(result,window){return result.hours.filter(item=>item.hour>=window.startHour&&item.hour<=window.endHour).sort((a,b)=>b.rawScore-a.rawScore||a.hour-b.hour)[0]}
  function primaryWindow(result,nowHour){const future=relevantWindows(result,nowHour);if(future.length)return future[0];return allWindows(result).sort((a,b)=>b.rawScore-a.rawScore||a.startHour-b.startHour)[0]||null}
  function periodMeta(hour){if(hour>=4&&hour<9)return{icon:'🌅',label:'朝'};if(hour>=9&&hour<16)return{icon:'☀️',label:'日中'};if(hour>=16&&hour<20)return{icon:'🌇',label:'夕方'};return{icon:'🌙',label:'夜'}}
  function reasonText(item){return(item?.reasons||[]).slice(0,2).join('＋')||`${item?.models?.[item?.dominantGroup]?.label||'対象魚'}が狙いやすい時間`}
  function primaryHTML(result,nowHour){const prohibited=wholeDayRestriction(result);if(prohibited)return`<section class="forecast-primary prohibited"><small>今日の本命</small><strong>本日は釣り禁止</strong><p>${prohibited.reason||'利用制限を優先してください。'}</p></section>`;const window=primaryWindow(result,nowHour);if(!window)return'<section class="forecast-primary empty"><small>今日の本命</small><strong>予測データなし</strong></section>';const item=bestHour(result,window),ended=isTodayResult(result)&&window.endHour<nowHour;return`<section class="forecast-primary${ended?' ended':''}"><small>${ended?'本日の本命は終了':'今日の本命'}</small><div class="forecast-primary-title"><strong>${windowLabel(window)}</strong><span>${fishIcons(window.score)}</span></div><p>${reasonText(item)}</p><div><b>${item?.targetSpecies?.join('・')||'対象魚未算出'}</b><em>${item?.recommendedMethod||'釣法未算出'}</em></div></section>`}
  function strategyHTML(result,nowHour){const ranked=relevantWindows(result,nowHour),restriction=isTodayResult(result)?blockingRestriction(result,nowHour):null;if(!ranked.length)return`<p class="forecast-ended">${restriction?.label||'本日の主な時合いは終了'}</p>`;const windows=[...ranked].sort((a,b)=>a.startHour-b.startHour);return`<div class="forecast-strategies">${windows.map(window=>{const rank=ranked.indexOf(window)+1,item=bestHour(result,window),period=periodMeta(window.startHour);return`<article class="forecast-strategy rank-${rank} level-${window.score}"><header><span>${period.icon} ${period.label}</span><strong>${windowLabel(window)}</strong><b>${fishIcons(window.score)}</b></header><div class="forecast-strategy-target"><p>${item?.targetSpecies?.join('・')||'対象魚未算出'}</p><em>${item?.recommendedMethod||'釣法未算出'}</em></div><small>${reasonText(item)}</small></article>`}).join('')}</div>`}
  function tideInsightHTML(result){const window=primaryWindow(result,localHour());if(!window)return'';const item=bestHour(result,window),reasons=(item?.reasons||[]).filter(reason=>/(潮|満潮|干潮|上げ|下げ)/.test(reason)).slice(0,2),phase=item?.feature?.tidePhase,parts=[phase,...reasons].filter(Boolean).filter((value,index,list)=>list.indexOf(value)===index);return parts.length?`<p class="forecast-tide-insight"><b>今日の潮</b>${parts.join('・')}</p>`:''}
  function tideLabelLayout(events,position){
    const placed=[];
    return events.map(item=>{
      const p=position(item),preferred=item.type==='high'?'above':'below';
      const box=(side,shift=0)=>({x:p.x+shift,top:side==='above'?p.y-32:p.y+2,bottom:side==='above'?p.y-2:p.y+32,side});
      const collides=candidate=>placed.some(other=>other.side===candidate.side&&Math.abs(other.x-candidate.x)<22&&candidate.top<other.bottom&&candidate.bottom>other.top);
      let side=preferred,shift=0,candidate=box(side);
      if(collides(candidate)){
        const alternate=side==='above'?'below':'above',alternateBox=box(alternate);
        if(!collides(alternateBox)){side=alternate;candidate=alternateBox}
        else{
          const shifts=p.x>50?[-3,3]:[3,-3],available=shifts.find(value=>!collides(box(side,value)));
          shift=available??shifts[0];candidate=box(side,shift)
        }
      };
      placed.push(candidate);
      const labelX=clamp(p.x+shift,0,100),edge=labelX<12?' edge-left':labelX>88?' edge-right':'',leader=shift<0?' shift-left':shift>0?' shift-right':'';
      return{item,p,labelX,className:`${item.type} ${side}${edge}${leader}`}
    })
  }
  function tideGraphHTML(tideDay,result){
    const values=(tideDay?.hourly||[]).map(Number),valid=values.filter(Number.isFinite);if(valid.length<2)return'<section class="forecast-tide-panel empty"><strong>潮汐データなし</strong></section>';
    const min=Math.min(...valid),max=Math.max(...valid),range=Math.max(1,max-min),point=(value,index)=>`${(index/23*100).toFixed(2)},${(86-(value-min)/range*62).toFixed(2)}`,points=values.map(point).join(' '),events=[...(tideDay.highs||[]).map(item=>({...item,type:'high',label:'満潮'})),...(tideDay.lows||[]).map(item=>({...item,type:'low',label:'干潮'}))],position=item=>{const [h,m]=item.time.split(':').map(Number);return{x:clamp((h+(m||0)/60)/23*100,0,100),y:clamp(86-(item.level-min)/range*62,8,88)}};
    const today=result&&isTodayResult(result),nowHour=localTime(),nowX=clamp(nowHour/23*100,0,100),solar=solarTimes(result),solarLines=[{type:'sunrise',hour:solar.sunrise},{type:'sunset',hour:solar.sunset}],labels=tideLabelLayout(events,position),eventXs=labels.map(label=>label.p.x),nowNearEvent=eventXs.some(x=>Math.abs(x-nowX)<11),displayNowX=clamp(nowX+(nowNearEvent?(nowX>50?4:-4):0),0,100);
    return`<section class="forecast-tide-panel" aria-label="${tideDay.station?.name||''}の24時間潮汐"><div class="forecast-tide-head"><div><small>潮の動き（24時間）</small><strong>${tideDay.station?.name||'観測地点'}・天文潮位</strong></div><span>${min}〜${max}cm</span></div><div class="forecast-tide-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="0時から23時の潮位曲線"><path class="forecast-tide-grid" d="M0 25H100 M0 55H100 M0 85H100"/>${solarLines.map(item=>{const x=clamp(item.hour/23*100,0,100);return`<line class="forecast-tide-solar-line ${item.type}" x1="${x.toFixed(2)}" y1="8" x2="${x.toFixed(2)}" y2="90"/>`}).join('')}${today?`<line class="forecast-tide-now-line" x1="${nowX.toFixed(2)}" y1="8" x2="${nowX.toFixed(2)}" y2="90"/>`:''}<polyline class="forecast-tide-line" points="${points}"/>${events.map(item=>{const p=position(item);return`<circle class="${item.type}" cx="${p.x.toFixed(2)}" cy="${p.y.toFixed(2)}" r="2.1"/>`}).join('')}</svg>${solarMarkersHTML(result,'tide',today?nowHour:null,eventXs)}${today?`<span class="forecast-tide-now${nowNearEvent?' avoid-event':''}" style="left:${displayNowX.toFixed(2)}%">今</span>`:''}${labels.map(({item,p,labelX,className})=>`<span class="forecast-tide-marker ${className}" style="left:${labelX.toFixed(2)}%;top:${p.y.toFixed(2)}%"><b>${item.label} ${item.time}</b><small>${item.level}cm</small></span>`).join('')}<div class="forecast-tide-times"><span>0時</span><span>6時</span><span>12時</span><span>18時</span><span>23時</span></div></div>${tideInsightHTML(result)}</section>`;
  }
  function conditionSummaryHTML(result){const current=result.hours[isTodayResult(result)?localHour():12]||result.hours[0],feature=current.feature,safety=feature.safety||{},weather=weatherLabels[feature.weatherCode]||'天気不明',wind=feature.windSpeed===null?'風不明':`風 ${feature.windSpeed.toFixed(1)}m/s`,wave=feature.wave===null?'波不明':`波 ${feature.wave.toFixed(1)}m`,tide=feature.tidePhase||'潮不明',safetyText=safety.label||safety.className||'安全確認';return`<section class="forecast-condition-summary ${safety.className||''}" aria-label="当日の安全・コンディション概要"><strong>${safety.symbol||'○'} ${safetyText}</strong><div><span>${weather}</span><span>${wind}</span><span>${wave}</span><span>${tide}</span></div></section>`}
  function restrictionHTML(result){const items=result.hours.flatMap(item=>item.feature?.safety?.restriction?.active||[]),unique=[...new Map(items.map(item=>[item.id,item])).values()];if(!unique.length)return'';return`<section class="forecast-restrictions" aria-label="釣り場の利用制限"><h5>🚧 利用制限</h5>${unique.map(item=>`<div class="${item.scope==='whole_spot'?'blocking':'partial'}"><strong>${item.label}</strong><span>${item.reason}</span>${item.areas?.length?`<small>対象：${item.areas.join('・')}</small>`:''}</div>`).join('')}</section>`}
  function detailHTML(item){const models=['pelagic','bottom','other'].map(group=>item.models[group]).filter(Boolean);return`<div class="forecast-detail-main"><small>選択した時間の答え</small><strong><span>総合期待度</span><b>${fishIcons(item.score)}</b><em>${item.score===null?'予測データなし':item.score===0?'期待薄':''}</em></strong><dl><div><dt>おすすめ</dt><dd>${item.recommendedMethod||'—'}</dd></div><div><dt>狙い</dt><dd>${item.targetSpecies?.join('・')||'—'}</dd></div></dl></div><div class="forecast-model-detail">${models.map(model=>`<span class="level-${model?.score===null?'unknown':model.score}"><b>${model.label}</b><em>${modelLevel(model)}</em><i>${fishIcons(model.score)}</i></span>`).join('')}</div><div class="forecast-detail-meta"><div class="forecast-reason-detail"><b>理由</b><span>${item.reasons.map(reason=>`・${reason}`).join('<br>')}</span></div><div class="forecast-confidence-detail">信頼度　${confidenceLabel[item.confidence]}</div></div>`}
  function render(root,spotProfile,result,source,tideDay){const nowHour=localHour(),prohibited=wholeDayRestriction(result);root.innerHTML=`<section class="forecast-card" aria-label="釣果期待度"><div class="forecast-head"><div><small>🐟 MFL FISHING EXPECTATION v1.7.4</small><h4>釣果期待度</h4></div><span>信頼度 ${confidenceLabel[result.confidence]||'低'}</span></div><p class="forecast-lead">公開釣果の傾向・季節・時間・潮・天候から算出した目安です。</p>${restrictionHTML(result)}${primaryHTML(result,nowHour)}${graphHTML(result)}<div class="forecast-graph-legend"><span>${prohibited?'🚫 利用制限を優先':'🐟 期待度'}</span><span>${prohibited?'期待度グラフは表示しません':'時間をタップして詳細'}</span></div><section class="forecast-strategy-section"><h5>時間帯別の狙い方</h5>${strategyHTML(result,nowHour)}</section>${tideGraphHTML(tideDay,result)}<div class="forecast-detail forecast-detail-prompt${prohibited?' prohibited':''}" aria-live="polite"><strong>${prohibited?'利用制限により時間別予測は停止しています':'時間をタップすると詳しい理由を表示します'}</strong></div><div class="forecast-legend"><span>${prohibited?'終日釣り禁止':'期待度0も算出結果です'}</span><span>安全情報を優先</span></div><p class="forecast-note">釣果を保証する予報ではありません。安全情報・利用制限を必ず優先してください。${source==='cache'?' 保存済み期待度を表示中。':''}</p><p class="forecast-updated">期待度データ更新：${displayDate(result.evidenceLastUpdated||result.baselineLastUpdated)}</p></section>`;const detail=root.querySelector('.forecast-detail');root.querySelectorAll('[data-forecast-hour]').forEach(button=>button.onclick=()=>{root.querySelectorAll('[data-forecast-hour]').forEach(item=>item.classList.toggle('selected',item===button));detail.classList.remove('forecast-detail-prompt');detail.innerHTML=detailHTML(result.hours[Number(button.dataset.forecastHour)])})}
  async function getForecast(spot){const date=localDate(),config=await window.MFLForecastData.loadConfig(),baseline=config.baselines.spots[spot.id],spotProfile=config.spots.spots[spot.id];if(!baseline||!spotProfile)throw new Error('期待度地点データなし');const evidenceLastUpdated=latestEvidence(baseline),version=`${config.baselines.version}:${config.spots.version}:${config.restrictions.version}`,cached=window.MFLForecastData.getCached(spot.id,date,version,evidenceLastUpdated);if(cached){const tideDay=await window.MFLTides.getTideDay(spot.id,date,spot);return{result:cached,spotProfile,source:'cache',tideDay}}const [tideDay,weather]=await Promise.all([window.MFLTides.getTideDay(spot.id,date,spot),window.MFLConditions.getForecastContext(spot,date)]);if(!tideDay?.available)throw new Error('潮汐データなし');const features=window.MFLForecastFeatures.normalize({spotId:spot.id,date,baseline,spotProfile,tideDay,weather,restrictions:config.restrictions}),result=window.MFLForecastEngine.predict(features,{baselineVersion:config.baselines.version,baselineLastUpdated:config.baselines.updated,evidenceLastUpdated});window.MFLForecastData.setCached(spot.id,date,version,evidenceLastUpdated,result);return{result,spotProfile,source:'live',tideDay}}
  async function mount(id,spot){const root=document.getElementById(id);if(!root||!supported.has(spot.id))return;root.innerHTML='<section class="forecast-card forecast-loading"><strong>🐟 釣果期待度を計算中…</strong></section>';try{const data=await getForecast(spot);if(root.isConnected)render(root,data.spotProfile,data.result,data.source,data.tideDay)}catch(error){console.warn('[MFL forecast] 期待度を表示できません',error);if(root.isConnected)root.innerHTML='<section class="forecast-card forecast-empty"><strong>期待度データなし</strong></section>'}}
  async function mountForecastView(summaryId,cardId,spot){const summary=document.getElementById(summaryId),card=document.getElementById(cardId);if(!summary||!card)return;card.innerHTML='<section class="forecast-card forecast-loading"><strong>🐟 釣果期待度を計算中…</strong></section>';try{const data=await getForecast(spot);if(!card.isConnected)return;summary.innerHTML=conditionSummaryHTML(data.result);render(card,data.spotProfile,data.result,data.source,data.tideDay)}catch(error){console.warn('[MFL forecast] 専用表示を表示できません',error);if(card.isConnected)card.innerHTML='<section class="forecast-card forecast-empty"><strong>期待度データなし</strong></section>'}}
  function overviewCard(spot,result){const overview=deriveOverview(result),name=displayNames[spot.id]||spot.name;return`<article class="forecast-place-card"><div><small>${spot.pref||''}</small><h3>${name}</h3></div><dl><div><dt>今日の期待度</dt><dd>${fishIcons(overview.score)}</dd></div><div><dt>狙い目</dt><dd>${overview.label}</dd></div><div><dt>おすすめ</dt><dd>${overview.method}</dd></div><div><dt>信頼度</dt><dd>${confidenceLabel[overview.confidence]||'低'}</dd></div></dl><button type="button" data-forecast-open="${spot.id}">詳しく見る</button></article>`}
  function spotsByPrefecture(spots,prefecture){return[...supported].map(spotId=>spots.find(spot=>spot.id===spotId)).filter(spot=>spot?.pref===prefecture)}
  async function mountHub(id,spots,openSpot){
    const root=document.getElementById(id);if(!root)return;
    const targets=[...supported].map(spotId=>spots.find(spot=>spot.id===spotId)).filter(Boolean),initialPrefecture=forecastPrefectures.find(prefecture=>spotsByPrefecture(spots,prefecture).length)||forecastPrefectures[0];
    root.innerHTML=`<section class="forecast-hub"><div class="forecast-hub-head"><small>MFL FISHING EXPECTATION</small><h2>今日はどこが期待できそうか</h2><p>県を選んで、これから狙える時間帯を比較します。</p></div><nav class="forecast-pref-tabs" aria-label="釣果期待度の都道府県"><div>${forecastPrefectures.map(prefecture=>`<button type="button" data-forecast-pref="${prefecture}" aria-pressed="${prefecture===initialPrefecture}">${prefecture}</button>`).join('')}</div><p class="forecast-pref-count" aria-live="polite"></p></nav><div class="forecast-place-grid">${spotsByPrefecture(spots,initialPrefecture).map(()=>'<article class="forecast-place-card loading">期待度を計算中…</article>').join('')}</div><p class="forecast-hub-note">公開釣果の傾向や当日の潮・天候から算出した目安です。コンディション順位とは独立した分類です。</p></section>`;
    const results=await Promise.all(targets.map(async spot=>{try{return{spot,...await getForecast(spot)}}catch(error){return{spot,error}}}));if(!root.isConnected)return;
    const renderPrefecture=prefecture=>{const items=results.filter(item=>item.spot.pref===prefecture),grid=root.querySelector('.forecast-place-grid');root.querySelectorAll('[data-forecast-pref]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.forecastPref===prefecture)));root.querySelector('.forecast-pref-count').textContent=`${prefecture}の予測地点 ${items.length}件`;grid.innerHTML=items.length?items.map(item=>item.result?overviewCard(item.spot,item.result):`<article class="forecast-place-card empty"><h3>${displayNames[item.spot.id]||item.spot.name}</h3><strong>期待度データなし</strong></article>`).join(''):`<div class="forecast-pref-empty"><strong>${prefecture}の予測地点は準備中です</strong><span>地点追加後、このタブに自動で表示されます。</span></div>`;grid.querySelectorAll('[data-forecast-open]').forEach(button=>button.onclick=()=>openSpot?.(button.dataset.forecastOpen))};
    root.querySelectorAll('[data-forecast-pref]').forEach(button=>button.onclick=()=>renderPrefecture(button.dataset.forecastPref));renderPrefecture(initialPrefecture)
  }
  window.MFLForecastUI={supported,forecastPrefectures,spotsByPrefecture,localDate,localHour,localTime,deriveOverview,allWindows,relevantWindows,wholeDayRestriction,primaryHTML,graphHTML,tideGraphHTML,tideLabelLayout,conditionSummaryHTML,getForecast,mount,mountForecastView,mountHub};
})();
