/* MFL fishing forecast UI v1.3 */
(function(){
  'use strict';
  const supported=new Set(['kashima','kemigawa_beach']),confidenceLabel={low:'低',medium:'中',high:'高'};
  const fishIcons=score=>score===null?'—':score===0?'<span class="forecast-faint-fish">🐟</span>':'🐟'.repeat(score);
  const hourLabel=hour=>`${hour}時`,modelLevel=model=>model?.score===null?'未算出':model.score>=3?'高':model.score===2?'中':model.score===1?'低':'期待薄';
  const localDate=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),map=Object.fromEntries(parts.map(x=>[x.type,x.value]));return`${map.year}-${map.month}-${map.day}`};
  const windowLabel=item=>item.startHour===item.endHour?hourLabel(item.startHour):`${item.startHour}〜${item.endHour}時`;
  const displayDate=value=>value?value.replace(/-/g,'/'):'—';
  const latestEvidence=baseline=>Object.values(baseline.models||{}).flatMap(model=>Object.values(model.season||{}).map(season=>season.evidence?.lastUpdated).filter(Boolean)).sort().at(-1)||'';
  function bestSummary(best,peakWindows){if(!best.length)return'<strong>今日は安全条件を優先</strong><span>無理に釣行をおすすめしません。</span>';const windows=peakWindows?.length?peakWindows:best.map(item=>({startHour:item.hour,endHour:item.hour}));return`<strong>狙い目 ${windows.map(windowLabel).join('・')}</strong><span>${best[0].recommendedMethod} / ${best[0].reasons.slice(0,2).join(' / ')}</span>`}
  function periodCards(profile,result){const bestByPeriod={};result.hours.filter(x=>x.score!==null&&x.recommended).forEach(item=>{const period=item.feature.period;if(!bestByPeriod[period]||item.rawScore>bestByPeriod[period].rawScore)bestByPeriod[period]=item});return['dawn','day','dusk','night'].filter(key=>bestByPeriod[key]).slice(0,3).map(key=>{const item=bestByPeriod[key],label=profile.periods[key]?.label||key;return`<div><small>${label}・${item.hour}時</small><strong>${item.targetSpecies.slice(0,2).join('・')}</strong><span>${item.recommendedMethod}</span></div>`}).join('')}
  function detailHTML(item){const models=['pelagic','bottom','other'].map(group=>item.models[group]).filter(Boolean);return`<div class="forecast-detail-main"><strong>総合期待度　${fishIcons(item.score)} ${item.score===null?'予測データなし':item.score===0?'期待薄':''}</strong><span>おすすめ　　${item.recommendedMethod||'—'}</span><span>狙い　　　　${item.targetSpecies?.join('・')||'—'}</span></div><div class="forecast-model-detail">${models.map(model=>`<span><b>${model.label}</b><em>${modelLevel(model)}</em></span>`).join('')}</div><div class="forecast-reason-detail"><b>理由</b><span>${item.reasons.map(reason=>`・${reason}`).join('<br>')}</span></div><div class="forecast-confidence-detail">信頼度　${confidenceLabel[item.confidence]}</div>`}
  function render(root,spotProfile,result,source){
    const nowHour=new Date().getHours(),hours=result.hours,isToday=hours[0]?.feature.date===localDate();
    root.innerHTML=`<section class="forecast-card" aria-label="MFL釣果予測"><div class="forecast-head"><div><small>🐟 MFL FISHING FORECAST v1.3</small><h4>今日の釣果期待度</h4></div><span>信頼度 ${confidenceLabel[result.confidence]||'低'}</span></div><p class="forecast-lead">魚の数が多い時間ほど、データ上の期待度が高い目安です。</p><div class="forecast-best">${bestSummary(result.best,result.peakWindows)}</div><div class="forecast-scroll" tabindex="0" aria-label="0時から23時の釣果期待度"><div class="forecast-hours">${hours.map(item=>`<button type="button" class="forecast-hour${isToday&&item.hour===nowHour?' current':''}${item.recommended?'':' unsafe'}" data-forecast-hour="${item.hour}" aria-label="${item.hour}時 期待度${item.score===null?'未算出':item.score} おすすめ${item.recommendedMethod||'なし'}${isToday&&item.hour===nowHour?' 現在時刻':''}"><small>${item.hour}${isToday&&item.hour===nowHour?'<u>今</u>':''}</small><b>${fishIcons(item.score)}</b><i>${item.recommendedMethod||'—'}</i><span>${item.score===null?'未算出':item.score===0?'期待薄':item.feature.tidePhase==='上げ潮'?'↗ 上げ':item.feature.tidePhase==='下げ潮'?'↘ 下げ':'→ 緩い'}</span><em>${item.feature.tideLevel===null?'—':item.feature.tideLevel+'cm'}</em></button>`).join('')}</div></div><div class="forecast-detail forecast-detail-prompt" aria-live="polite"><strong>時間をタップすると詳しい理由を表示します</strong></div><div class="forecast-periods">${periodCards(spotProfile,result)}</div><div class="forecast-legend"><span>🐟 総合期待度</span><span>小さな文字＝おすすめ釣法</span><span>↗↘ 潮の動き</span></div><p class="forecast-note">釣果を保証するものではありません。天候・波・施設規制など安全情報を必ず優先してください。${source==='cache'?' 保存済み予測を表示中。':''}</p><p class="forecast-updated">予測データ更新：${displayDate(result.evidenceLastUpdated||result.baselineLastUpdated)}</p></section>`;
    const detail=root.querySelector('.forecast-detail');root.querySelectorAll('[data-forecast-hour]').forEach(button=>button.onclick=()=>{root.querySelectorAll('[data-forecast-hour]').forEach(x=>x.classList.toggle('selected',x===button));detail.classList.remove('forecast-detail-prompt');detail.innerHTML=detailHTML(hours[Number(button.dataset.forecastHour)])});
    const focus=result.best[0]||(isToday?hours[nowHour]:hours[0]),button=focus&&root.querySelector(`[data-forecast-hour="${focus.hour}"]`),scroller=root.querySelector('.forecast-scroll');requestAnimationFrame(()=>{if(button&&scroller)scroller.scrollLeft=Math.max(0,button.offsetLeft-scroller.clientWidth/2+button.offsetWidth/2)})
  }
  async function mount(id,spot){const root=document.getElementById(id);if(!root||!supported.has(spot.id))return;root.innerHTML='<section class="forecast-card forecast-loading"><strong>🐟 MFL釣果予測を計算中…</strong><span>魚種傾向・潮・マヅメ・天候を確認しています。</span></section>';try{const date=localDate(),config=await window.MFLForecastData.loadConfig(),baseline=config.baselines.spots[spot.id],spotProfile=config.spots.spots[spot.id];if(!baseline||!spotProfile)throw new Error('予測地点データなし');const evidenceLastUpdated=latestEvidence(baseline),version=`${config.baselines.version}:${config.spots.version}`,cached=window.MFLForecastData.getCached(spot.id,date,version,evidenceLastUpdated);if(cached){if(root.isConnected)render(root,spotProfile,cached,'cache');return}const [tideDay,weather]=await Promise.all([window.MFLTides.getTideDay(spot.id,date,spot),window.MFLConditions.getForecastContext(spot,date)]);if(!tideDay?.available)throw new Error('潮汐データなし');const features=window.MFLForecastFeatures.normalize({spotId:spot.id,date,baseline,spotProfile,tideDay,weather}),result=window.MFLForecastEngine.predict(features,{baselineVersion:config.baselines.version,baselineLastUpdated:config.baselines.updated,evidenceLastUpdated});window.MFLForecastData.setCached(spot.id,date,version,evidenceLastUpdated,result);if(root.isConnected)render(root,spotProfile,result,'live')}catch(error){console.warn('[MFL forecast] 予測を表示できません',error);if(root.isConnected)root.innerHTML='<section class="forecast-card forecast-empty"><strong>予測データなし</strong><span>通信または当日の予測材料を確認できませんでした。</span></section>'}}
  window.MFLForecastUI={supported,mount};
})();
